# SOURCE MODEL (SM) RAW TRAINING DATA : FEATURE SELECTIONÂ¶

## SOURCE MODEL (SM) - RAW TRAINING DATA WITH PRE-PROCESSED TARGET

## Importing Python Libraries

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

print("Import Completed")

Import Completed

## Importing the Source Model (SM) Raw Training Data csv File

In [2]:
source_model_raw_train = pd.read_csv("/Users/vidhyalakshmiparthasarathy/.CMVolumes/Google-Drive-pbvidhyauk6/QMUL_MSc_Project/credit_risk_scoring_project/data/source_model_raw_data/source_model_raw_train.csv")

print("Data Export Completed")

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (20) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Data Export Completed

In [3]:
# Sets the pandas dataframe options to display all columns/ rows.

pd.options.display.max_columns = None
#pd.options.display.max_rows = None

print("Execution Completed")

Execution Completed

In [4]:
# Checking the size of the dataset

source_model_raw_train.shape

(419426, 155)

In [5]:
# Checking the first 3 column names of the dataset

source_model_raw_train.columns[[0, 1, 2]]

Index(['Unnamed: 0', 'id', 'member_id'], dtype='object')

In [6]:
# Removing the first index column from the dataset

source_model_raw_train.drop(source_model_raw_train.columns[0], axis = 1, inplace = True)

print("Execution Completed")

Execution Completed

In [7]:
# Re-checking the size of the dataset

source_model_raw_train.shape

(419426, 154)

In [8]:
# Displying the first 5 data instances

source_model_raw_train.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,fico_range_low,fico_range_high,last_fico_range_high,last_fico_range_low,fico_average_latest,fico_score_status_good-_good+,fico_score_status
0,74565928,NaN,30000.0,30000.0,30000.0,36 months,19.53,1107.74,D,D5,Manager,2 years,RENT,60000.0,Verified,Mar-16,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,907xx,CA,9.54,0.0,Apr-05,1.0,29.0,NaN,18.0,0.0,15694.0,20.8,22.0,w,0.00,0.00,39845.904740,39845.90,30000.00,9845.90,0.0,0.00,0.0000,Mar-19,1107.55,NaN,Mar-19,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,1459.0,166376.0,3.0,0.0,0.0,0.0,39.0,0.0,NaN,4.0,10.0,5692.0,21.0,75300.0,0.0,0.0,6.0,10.0,9787.0,52771.0,22.7,0.0,0.0,131.0,120.0,3.0,3.0,1.0,3.0,NaN,1.0,NaN,0.0,8.0,9.0,14.0,14.0,4.0,17.0,17.0,9.0,18.0,0.0,0.0,0.0,4.0,94.7,0.0,0.0,0.0,241729.0,15694.0,68300.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,690.0,694.0,714.0,710.0,712,Good+,1
1,137865468,NaN,16000.0,16000.0,16000.0,36 months,6.67,491.63,A,A2,Cash Management Specialist 2,< 1 year,MORTGAGE,60000.0,Not Verified,Aug-18,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,750xx,TX,11.38,0.0,May-05,0.0,NaN,NaN,6.0,0.0,27068.0,62.5,12.0,w,13133.68,13133.68,3429.550000,3429.55,2866.32,563.23,0.0,0.00,0.0000,Mar-19,491.63,Apr-19,Mar-19,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,183276.0,0.0,0.0,0.0,0.0,38.0,0.0,NaN,0.0,0.0,19190.0,63.0,43300.0,0.0,0.0,0.0,1.0,30546.0,8123.0,76.6,0.0,0.0,138.0,158.0,59.0,12.0,2.0,59.0,NaN,14.0,NaN,0.0,3.0,4.0,3.0,4.0,2.0,5.0,8.0,4.0,6.0,0.0,0.0,0.0,1.0,100.0,33.3,0.0,0.0,201700.0,27068.0,34700.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN,705.0,709.0,699.0,695.0,697,Good+,1
2,65754356,NaN,14400.0,14400.0,14400.0,60 months,12.59,324.63,C,C2,Occupational Health Nurse,< 1 year,RENT,65000.0,Source Verified,Nov-15,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,770xx,TX,26.97,0.0,Oct-02,1.0,29.0,NaN,6.0,0.0,3191.0,41.4,23.0,f,0.00,0.00,7468.750000,7468.75,2803.41,2050.93,0.0,2614.41,470.5938,Mar-17,324.63,NaN,Aug-17,0.0,29.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,25900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7700.0,NaN,NaN,NaN,3.0,4317.0,28.0,98.9,0.0,0.0,157.0,89.0,3.0,3.0,0.0,9.0,NaN,3.0,29.0,1.0,1.0,2.0,1.0,4.0,10.0,3.0,13.0,2.0,6.0,0.0,0.0,0.0,2.0,90.9,100.0,0.0,0.0,70897.0,25900.0,2500.0,63197.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,670.0,674.0,554.0,550.0,552,Good-,0
3,67978904,NaN,5600.0,5600.0,5600.0,36 months,13.44,189.88,C,C3,Sheet metal,2 years,RENT,57000.0,Not Verified,Dec-15,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,028xx,RI,11.94,0.0,Jan-96,1.0,NaN,33.0,8.0,3.0,3770.0,73.9,10.0,w,0.00,0.00,6609.607245,6609.61,5600.00,1009.61,0.0,0.00,0.0000,Oct-17,2822.46,NaN,Dec-17,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,16918.0,1.0,2.0,0.0,1.0,22.0,13148.0,47.0,4.0,4.0,2457.0,52.0,5100.0,2.0,0.0,7.0,5.0,2417.0,677.0,84.3,0.0,0.0,135.0,26.0,5.0,5.0,0.0,8.0,NaN,1.0,NaN,0.0,4.0,5.0,4.0,4.0,4.0,5.0,5.0,5.0,8.0,0.0,0.0,0.0,4.0,100.0,50.0,3.0,0.0,32824.0,16918.0,4300.0,27724.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,665.0,669.0,664.0,660.0,662,Good-,0
4,65632165,NaN,23100.0,23100.0,23100.0,60 months,18.20,589.11,E,E1,Saturation Technican,5 years,MORTGAGE,100000.0,Verified,Nov-15,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,366xx,AL,31.48,1.0,Aug-10,0.0,21.0,NaN,10.0,0.0,9088.0,80.4,15.0,w,0.00,0.00,14681.040000,14681.04,7192.92,7488.12,0.0,0.00,0.0000,Dec-17,589.11,NaN,Mar-19,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,270.0,179712.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11300.0,NaN,NaN,NaN,4.0,17971.0,1234.0,84.0,0.0,0.0,63.0,39.0,14.0,6.0,1.0,14.0,NaN,9.0,NaN,0.0,3.0,4.0,3.0,3.0,10.0,4.0,4.0,4.0,10.0,0.0,0.0,0.0,2.0,93.3,66.7,0.0,0.0,212887.0,104671.0,7700.0,115100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,675.0,679.0,639.0,635.0,637,Good-,0

# FEATURE SELECTION

#### Below are the list of initial shortlisted features selected that are relevant to FICO Scores; based on Credit Risk Scoring domain expertise and knowledge/information gathered from FICO official website and 3 credit bureaus (Experian, Equifax and Transunion) official websites.

#### This includes both the input/independent (predictors) and target/dependent (label) feature "fico_score_status".

#### These features are based on the FICO's 5 factors related to Credit Risk Scoring and Non-FICO factors related to lender's internal
> #### 1. FICO Factor 1      - Payment History            - (35%)
> #### 2. FICO Factor 2      - Amount Owed                - (30%)
> #### 3. FICO Factor 3      - Length of Credit History   - (15%)
> #### 4. FICO Factor 4      - Credit Mix                 - (10%)
> #### 5. FICO Factor 5      - New Credit                 - (10%)
> #### 6. Non-FICO Factor 6  - Lender's Internal          - (Custom)    - It varies from one lender (Financial Institution) to an other lender

In [9]:
# Initial Shorlisted Featues List related to FICO Scores and Lender's Internal for the Source Model (SM)

sm_initial_shortlisted_features_list = ['delinq_2yrs', 'mths_since_last_delinq', 'mths_since_last_record', 'pub_rec',
                                         'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 'acc_now_delinq',
                                         'chargeoff_within_12_mths', 'delinq_amnt', 'mths_since_recent_bc_dlq',
                                         'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_tl_120dpd_2m', 'num_tl_30dpd',
                                         'num_tl_90g_dpd_24m', 'pub_rec_bankruptcies',
                                         'revol_bal', 'revol_util', 'tot_cur_bal', 'total_bal_il', 'il_util', 'max_bal_bc', 'avg_cur_bal',
                                         'num_rev_tl_bal_gt_0', 'percent_bc_gt_75', 'total_bal_ex_mort',
                                         'earliest_cr_line', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op',
                                         'open_acc','total_acc', 'open_il_24m', 'open_rv_24m', 'mort_acc', 'num_actv_bc_tl', 'num_actv_rev_tl',
                                         'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_sats',
                                         'inq_last_6mths', 'inq_last_12m', 'acc_open_past_24mths', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
                                         'mths_since_recent_bc', 'mths_since_recent_inq', 'num_tl_op_past_12m', 'open_il_12m', 'mths_since_rcnt_il', 
                                         'open_rv_12m',
                                         'emp_length', 'home_ownership', 'annual_inc', 'dti',
                                         'fico_score_status']
                        
# Total Number of Initial Shortlisted Features
print("Total Number of Initial Shortlisted Features including the Target: ", len(sm_initial_shortlisted_features_list))

print("Execution Completed")

Total Number of Initial Shortlisted Features including the Target:  59
Execution Completed

In [10]:
# Checking the datatypes of the Initial Shortlisted Features

for feat in sm_initial_shortlisted_features_list:
    print(feat, ".....", source_model_raw_train.dtypes[feat])

delinq_2yrs ..... float64
mths_since_last_delinq ..... float64
mths_since_last_record ..... float64
pub_rec ..... float64
total_rec_late_fee ..... float64
recoveries ..... float64
collection_recovery_fee ..... float64
acc_now_delinq ..... float64
chargeoff_within_12_mths ..... float64
delinq_amnt ..... float64
mths_since_recent_bc_dlq ..... float64
mths_since_recent_revol_delinq ..... float64
num_accts_ever_120_pd ..... float64
num_tl_120dpd_2m ..... float64
num_tl_30dpd ..... float64
num_tl_90g_dpd_24m ..... float64
pub_rec_bankruptcies ..... float64
revol_bal ..... float64
revol_util ..... float64
tot_cur_bal ..... float64
total_bal_il ..... float64
il_util ..... float64
max_bal_bc ..... float64
avg_cur_bal ..... float64
num_rev_tl_bal_gt_0 ..... float64
percent_bc_gt_75 ..... float64
total_bal_ex_mort ..... float64
earliest_cr_line ..... object
mo_sin_old_il_acct ..... float64
mo_sin_old_rev_tl_op ..... float64
open_acc ..... float64
total_acc ..... float64
open_il_24m ..... float64
open_rv_24m ..... float64
mort_acc ..... float64
num_actv_bc_tl ..... float64
num_actv_rev_tl ..... float64
num_bc_sats ..... float64
num_bc_tl ..... float64
num_il_tl ..... float64
num_op_rev_tl ..... float64
num_rev_accts ..... float64
num_sats ..... float64
inq_last_6mths ..... float64
inq_last_12m ..... float64
acc_open_past_24mths ..... float64
mo_sin_rcnt_rev_tl_op ..... float64
mo_sin_rcnt_tl ..... float64
mths_since_recent_bc ..... float64
mths_since_recent_inq ..... float64
num_tl_op_past_12m ..... float64
open_il_12m ..... float64
mths_since_rcnt_il ..... float64
open_rv_12m ..... float64
emp_length ..... object
home_ownership ..... object
annual_inc ..... float64
dti ..... float64
fico_score_status ..... int64

## Individual Shortlisted Features with respect to FICO's 5 factors and Lender's Internal factors

In [11]:
# List of features that are relevant to FICO Scores : "Payment History" Factor-1

sm_fico_payment_history_inputs = ['delinq_2yrs', 'mths_since_last_delinq', 'mths_since_last_record', 'pub_rec', 'total_rec_late_fee',
                              'recoveries', 'collection_recovery_fee', 'acc_now_delinq', 'chargeoff_within_12_mths', 'delinq_amnt',
                              'mths_since_recent_bc_dlq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_tl_120dpd_2m',
                              'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'pub_rec_bankruptcies']

sm_fico_payment_history_output = ['fico_score_status']

sm_fico_payment_history_inputs_output = ['delinq_2yrs', 'mths_since_last_delinq', 'mths_since_last_record', 'pub_rec', 'total_rec_late_fee',
                                    'recoveries', 'collection_recovery_fee', 'acc_now_delinq', 'chargeoff_within_12_mths', 'delinq_amnt',
                                    'mths_since_recent_bc_dlq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_tl_120dpd_2m',
                                    'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'pub_rec_bankruptcies', 'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 1 'Payment History': ", len(sm_fico_payment_history_inputs))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 1 'Payment History':  17
Execution Completed

In [12]:
# List of features that are relevant to FICO Scores : "Amount Owed" Factor-2

sm_fico_amount_owed_inputs = ['revol_bal', 'revol_util', 'tot_cur_bal', 'total_bal_il', 'il_util', 'max_bal_bc', 'avg_cur_bal',
                          'num_rev_tl_bal_gt_0', 'percent_bc_gt_75', 'total_bal_ex_mort']

sm_fico_amount_owed_output = ['fico_score_status']

sm_fico_amount_owed_inputs_output = ['revol_bal', 'revol_util', 'tot_cur_bal', 'total_bal_il', 'il_util', 'max_bal_bc', 'avg_cur_bal',
                                 'num_rev_tl_bal_gt_0', 'percent_bc_gt_75', 'total_bal_ex_mort', 'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 2 'Amount Owed': ", len(sm_fico_amount_owed_inputs))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 2 'Amount Owed':  10
Execution Completed

In [13]:
# List of features that are relevant to FICO Scores : "Length of Credit History" Factor-3

sm_fico_length_of_credit_history_inputs = ['earliest_cr_line', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op']

sm_fico_length_of_credit_history_output = ['fico_score_status']

sm_fico_length_of_credit_history_inputs_output = ['earliest_cr_line', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 3 'Length of Credit History': ", len(sm_fico_length_of_credit_history_inputs))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 3 'Length of Credit History':  3
Execution Completed

In [14]:
# List of features that are relevant to FICO Scores : "Credit Mix" Factor-4

sm_fico_credit_mix_inputs = ['open_acc', 'total_acc', 'open_il_24m', 'open_rv_24m', 'mort_acc', 'num_actv_bc_tl', 'num_actv_rev_tl',
                         'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_sats']

sm_fico_credit_mix_output = ['fico_score_status']

sm_fico_credit_mix_inputs_output = ['open_acc', 'total_acc', 'open_il_24m', 'open_rv_24m', 'mort_acc', 'num_actv_bc_tl', 'num_actv_rev_tl',
                                'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_sats', 'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 4 'Credit Mix': ", len(sm_fico_credit_mix_inputs))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 4 'Credit Mix':  13
Execution Completed

In [15]:
# List of features that are relevant to FICO Scores : "New Credit" Factor-5

sm_fico_new_credit_inputs = ['inq_last_6mths', 'inq_last_12m', 'acc_open_past_24mths', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
                            'mths_since_recent_bc', 'mths_since_recent_inq', 'num_tl_op_past_12m', 'open_il_12m', 'mths_since_rcnt_il', 'open_rv_12m']

sm_fico_new_credit_output = ['fico_score_status']

sm_fico_new_credit_inputs_output = ['inq_last_6mths', 'inq_last_12m', 'acc_open_past_24mths', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
                                   'mths_since_recent_bc', 'mths_since_recent_inq', 'num_tl_op_past_12m', 'open_il_12m', 'mths_since_rcnt_il', 
                                   'open_rv_12m', 'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 5 'New Credit': ", len(sm_fico_new_credit_inputs))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 5 'New Credit':  11
Execution Completed

In [16]:
# List of features that are relevant to Non-FICO : "Lenders Internal" Factor 6

sm_non_fico_lenders_internal_inputs = ['emp_length_int', 'home_ownership_int', 'annual_inc', 'dti']

sm_non_fico_lenders_internal_output = ['fico_score_status']

sm_non_fico_lenders_internal_inputs_output = ['emp_length_int', 'home_ownership_int', 'annual_inc', 'dti',
                                          'fico_score_status']

print("Total Number of Initial Shorlisted Features related to Non-FICO Score Factor 6 'Lenders Internal': ", len(sm_non_fico_lenders_internal_inputs))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to Non-FICO Score Factor 6 'Lenders Internal':  4
Execution Completed

## Creating a new Dataframe which includes only the initial shortlisted features and the target variable

In [17]:
source_model_raw_train_feature_selection = source_model_raw_train[sm_initial_shortlisted_features_list].copy()

print("Execution Completed")

Execution Completed

In [18]:
# Sets the pandas dataframe options to display all columns/rows

pd.options.display.max_columns = None
#pd.options.display.max_rows = None

print("Execution Completed")

Execution Completed

In [19]:
# Checking the size of the dataset

source_model_raw_train_feature_selection.shape

(419426, 59)

In [20]:
# Displying the dataframe

source_model_raw_train_feature_selection

,delinq_2yrs,mths_since_last_delinq,mths_since_last_record,pub_rec,total_rec_late_fee,recoveries,collection_recovery_fee,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,mths_since_recent_bc_dlq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,pub_rec_bankruptcies,revol_bal,revol_util,tot_cur_bal,total_bal_il,il_util,max_bal_bc,avg_cur_bal,num_rev_tl_bal_gt_0,percent_bc_gt_75,total_bal_ex_mort,earliest_cr_line,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,open_acc,total_acc,open_il_24m,open_rv_24m,mort_acc,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_sats,inq_last_6mths,inq_last_12m,acc_open_past_24mths,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mths_since_recent_bc,mths_since_recent_inq,num_tl_op_past_12m,open_il_12m,mths_since_rcnt_il,open_rv_12m,emp_length,home_ownership,annual_inc,dti,fico_score_status
0,0.0,29.0,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,15694.0,20.8,166376.0,0.0,NaN,5692.0,9787.0,9.0,0.0,15694.0,Apr-05,131.0,120.0,18.0,22.0,0.0,10.0,1.0,8.0,9.0,14.0,14.0,4.0,17.0,17.0,18.0,1.0,6.0,10.0,3.0,3.0,3.0,1.0,4.0,0.0,39.0,4.0,2 years,RENT,60000.0,9.54,1
1,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,27068.0,62.5,183276.0,0.0,NaN,19190.0,30546.0,4.0,33.3,27068.0,May-05,138.0,158.0,6.0,12.0,0.0,0.0,2.0,3.0,4.0,3.0,4.0,2.0,5.0,8.0,6.0,0.0,0.0,1.0,59.0,12.0,59.0,14.0,1.0,0.0,38.0,0.0,< 1 year,MORTGAGE,60000.0,11.38,1
2,0.0,29.0,NaN,0.0,0.0,2614.41,470.5938,0.0,0.0,0.0,NaN,29.0,1.0,0.0,0.0,0.0,0.0,3191.0,41.4,25900.0,NaN,NaN,NaN,4317.0,2.0,100.0,25900.0,Oct-02,157.0,89.0,6.0,23.0,NaN,NaN,0.0,1.0,2.0,1.0,4.0,10.0,3.0,13.0,6.0,1.0,NaN,3.0,3.0,3.0,9.0,3.0,2.0,NaN,NaN,NaN,< 1 year,RENT,65000.0,26.97,0
3,0.0,NaN,33.0,3.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,3.0,3770.0,73.9,16918.0,13148.0,47.0,2457.0,2417.0,5.0,50.0,16918.0,Jan-96,135.0,26.0,8.0,10.0,1.0,4.0,0.0,4.0,5.0,4.0,4.0,4.0,5.0,5.0,8.0,1.0,7.0,5.0,5.0,5.0,8.0,1.0,4.0,0.0,22.0,4.0,2 years,RENT,57000.0,11.94,0
4,1.0,21.0,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,9088.0,80.4,179712.0,NaN,NaN,NaN,17971.0,4.0,66.7,104671.0,Aug-10,63.0,39.0,10.0,15.0,NaN,NaN,1.0,3.0,4.0,3.0,3.0,10.0,4.0,4.0,10.0,0.0,NaN,4.0,14.0,6.0,14.0,9.0,2.0,NaN,NaN,NaN,5 years,MORTGAGE,100000.0,31.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419421,1.0,15.0,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,15.0,15.0,0.0,0.0,0.0,0.0,0.0,3604.0,90.1,80693.0,77089.0,NaN,3604.0,40347.0,1.0,100.0,80693.0,Jul-08,90.0,114.0,2.0,3.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,101.0,90.0,101.0,NaN,0.0,0.0,90.0,0.0,< 1 year,RENT,28000.0,6.39,0
419422,1.0,NaN,108.0,1.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,1.0,0.0,6930.0,79.0,133352.0,NaN,NaN,NaN,12122.0,4.0,33.3,63530.0,Jul-90,170.0,40.0,11.0,20.0,NaN,NaN,1.0,3.0,4.0,4.0,4.0,10.0,4.0,5.0,11.0,2.0,NaN,9.0,5.0,4.0,5.0,2.0,3.0,NaN,NaN,NaN,< 1 year,MORTGAGE,75000.0,28.83,1
419423,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,13948.0,62.8,51670.0,NaN,NaN,NaN,8612.0,5.0,100.0,51670.0,Jan-93,24.0,263.0,6.0,18.0,NaN,NaN,2.0,2.0,5.0,2.0,7.0,1.0,5.0,11.0,6.0,1.0,NaN,4.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1 year,RENT,110000.0,16.88,1
419424,0.0,34.0,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,34.0,34.0,0.0,0.0,0.0,0.0,0.0,13977.0,87.4,258430.0,2107.0,57.0,0.0,86143.0,1.0,NaN,16084.0,Nov-03,127.0,163.0,3.0,19.0,2.0,0.0,3.0,0.0,1.0,0.0,7.0,7.0,1.0,9.0,3.0,0.0,0.0,3.0,37.0,13.0,NaN,NaN,0.0,0.0,13.0,0.0,3 years,MORTGAGE,75000.0,5.87,1
419425,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,6383.0,76.0,183176.0,NaN,NaN,NaN,14090.0,5.0,100.0,76500.0,Aug-09,75.0,67.0,13.0,20.0,NaN,NaN,1.0,1.0,5.0,1.0,2.0,9.0,6.0,10.0,13.0,0.0,NaN,7.0,6.0,5.0,67.0,5.0,4.0,NaN,NaN,NaN,1 year,MORTGAGE,53114.0,31.99,1

In [21]:
# Checking the datatypes of the dataframe

for feat in source_model_raw_train_feature_selection.columns:
    print(feat, ".....", source_model_raw_train_feature_selection.dtypes[feat])

delinq_2yrs ..... float64
mths_since_last_delinq ..... float64
mths_since_last_record ..... float64
pub_rec ..... float64
total_rec_late_fee ..... float64
recoveries ..... float64
collection_recovery_fee ..... float64
acc_now_delinq ..... float64
chargeoff_within_12_mths ..... float64
delinq_amnt ..... float64
mths_since_recent_bc_dlq ..... float64
mths_since_recent_revol_delinq ..... float64
num_accts_ever_120_pd ..... float64
num_tl_120dpd_2m ..... float64
num_tl_30dpd ..... float64
num_tl_90g_dpd_24m ..... float64
pub_rec_bankruptcies ..... float64
revol_bal ..... float64
revol_util ..... float64
tot_cur_bal ..... float64
total_bal_il ..... float64
il_util ..... float64
max_bal_bc ..... float64
avg_cur_bal ..... float64
num_rev_tl_bal_gt_0 ..... float64
percent_bc_gt_75 ..... float64
total_bal_ex_mort ..... float64
earliest_cr_line ..... object
mo_sin_old_il_acct ..... float64
mo_sin_old_rev_tl_op ..... float64
open_acc ..... float64
total_acc ..... float64
open_il_24m ..... float64
open_rv_24m ..... float64
mort_acc ..... float64
num_actv_bc_tl ..... float64
num_actv_rev_tl ..... float64
num_bc_sats ..... float64
num_bc_tl ..... float64
num_il_tl ..... float64
num_op_rev_tl ..... float64
num_rev_accts ..... float64
num_sats ..... float64
inq_last_6mths ..... float64
inq_last_12m ..... float64
acc_open_past_24mths ..... float64
mo_sin_rcnt_rev_tl_op ..... float64
mo_sin_rcnt_tl ..... float64
mths_since_recent_bc ..... float64
mths_since_recent_inq ..... float64
num_tl_op_past_12m ..... float64
open_il_12m ..... float64
mths_since_rcnt_il ..... float64
open_rv_12m ..... float64
emp_length ..... object
home_ownership ..... object
annual_inc ..... float64
dti ..... float64
fico_score_status ..... int64

In [22]:
# Checking the null "NaN" values (missing values) in the dataframe

pd.set_option('display.max_rows',None)
source_model_raw_train_feature_selection.isna().sum()

delinq_2yrs                            0
mths_since_last_delinq            210854
mths_since_last_record            349485
pub_rec                                0
total_rec_late_fee                     0
recoveries                             0
collection_recovery_fee                0
acc_now_delinq                         0
chargeoff_within_12_mths               0
delinq_amnt                            0
mths_since_recent_bc_dlq          319484
mths_since_recent_revol_delinq    276771
num_accts_ever_120_pd                  0
num_tl_120dpd_2m                   17834
num_tl_30dpd                           0
num_tl_90g_dpd_24m                     0
pub_rec_bankruptcies                   0
revol_bal                              0
revol_util                           297
tot_cur_bal                            0
total_bal_il                      159713
il_util                           197402
max_bal_bc                        159713
avg_cur_bal                           13
num_rev_tl_bal_gt_0                    0
percent_bc_gt_75                    4783
total_bal_ex_mort                      0
earliest_cr_line                       0
mo_sin_old_il_acct                 12883
mo_sin_old_rev_tl_op                   0
open_acc                               0
total_acc                              0
open_il_24m                       159713
open_rv_24m                       159713
mort_acc                               0
num_actv_bc_tl                         0
num_actv_rev_tl                        0
num_bc_sats                            0
num_bc_tl                              0
num_il_tl                              0
num_op_rev_tl                          0
num_rev_accts                          0
num_sats                               0
inq_last_6mths                         0
inq_last_12m                      159713
acc_open_past_24mths                   0
mo_sin_rcnt_rev_tl_op                  0
mo_sin_rcnt_tl                         0
mths_since_recent_bc                4422
mths_since_recent_inq              46830
num_tl_op_past_12m                     0
open_il_12m                       159713
mths_since_rcnt_il                167956
open_rv_12m                       159713
emp_length                         27892
home_ownership                         0
annual_inc                             0
dti                                  339
fico_score_status                      0
dtype: int64

## Pre-Processing String Data Type Features into Numeric Features to Support Implementation of the Feature Selection Method

In [23]:
# Filtering the list of features which are of data type "string" (object)

for feat in source_model_raw_train_feature_selection.columns:
    if source_model_raw_train_feature_selection.dtypes[feat] == "object":
        print(feat, ".....", source_model_raw_train_feature_selection.dtypes[feat])

earliest_cr_line ..... object
emp_length ..... object
home_ownership ..... object

### We will be pre-processing the above listed 3 input "string" data type features into numeric format.

## 1. Pre-processing the String Data Type Input Feature "earliest_cr_line" (Date Type Input Feature) to Numeric Format

In [24]:
# Display the "earliest_cr_line" column values for 20 random data instances

source_model_raw_train_feature_selection['earliest_cr_line'].sample(20)

81499     Apr-05
214162    May-85
217683    Mar-00
339496    Aug-02
159309    Apr-10
184255    Sep-80
109596    Aug-99
412877    Nov-02
178547    May-96
369239    Sep-03
283745    May-05
266199    Apr-10
230925    Jan-04
293986    Aug-87
108605    Aug-01
144214    Jun-04
349007    Aug-04
186981    Nov-94
43657     Aug-10
119801    Aug-95
Name: earliest_cr_line, dtype: object

In [25]:
# Extract the date and the time from the Date Type String Variable "earliest_cr_line" in to a new pandas dataframe column

source_model_raw_train_feature_selection['earliest_cr_line_date'] = pd.to_datetime(source_model_raw_train_feature_selection['earliest_cr_line'], format = '%b-%y')

print("Execution Completed")

Execution Completed

In [26]:
# Verifying the date and time created in the new column "earliest_cr_line_date" for the first 5 data instances

source_model_raw_train_feature_selection['earliest_cr_line_date'][:5]

0   2005-04-01
1   2005-05-01
2   2002-10-01
3   1996-01-01
4   2010-08-01
Name: earliest_cr_line_date, dtype: datetime64[ns]

In [27]:
# Converting the date an time into number of days format; by calculating the difference between the given date and current date as 1st September 2021

pd.to_datetime('2021-09-01') - source_model_raw_train_feature_selection['earliest_cr_line_date']

print("Execution Completed")

Execution Completed

In [28]:
# Calculating the difference between the given date and current date as 1st September 2021 in months format, then convert it into numeric format and round it
# Saving the results to a new column named "months_since_earliest_cr_line"

source_model_raw_train_feature_selection['months_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2021-09-01') - source_model_raw_train_feature_selection['earliest_cr_line_date']) / np.timedelta64(1, 'M')))

print("Execution Completed")

Execution Completed

In [29]:
# Verifying the first 5 data instances of the new column "months_since_earliest_cr_line"

source_model_raw_train_feature_selection['months_since_earliest_cr_line'][:5]

0    197.0
1    196.0
2    227.0
3    308.0
4    133.0
Name: months_since_earliest_cr_line, dtype: float64

In [30]:
# Displaying the descriptive statistics of the values in the column "months_since_earliest_cr_line"

source_model_raw_train_feature_selection['months_since_earliest_cr_line'].describe()

count    419426.000000
mean        256.051306
std          99.639925
min        -567.000000
25%         194.000000
50%         241.000000
75%         307.000000
max         632.000000
Name: months_since_earliest_cr_line, dtype: float64

In [31]:
# Displaying only the 3 columns w.r.t "earliest_cr_line" attribute and displaying only the rows which has negative values calculated for the data differences
# Displaying results for a random sample of 20 data instances

source_model_raw_train_feature_selection.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'months_since_earliest_cr_line']][source_model_raw_train_feature_selection['months_since_earliest_cr_line'] < 0].sample(20)

       earliest_cr_line earliest_cr_line_date  months_since_earliest_cr_line
39642            Nov-61            2061-11-01                         -482.0
307567           Sep-68            2068-09-01                         -564.0
107059           Jan-67            2067-01-01                         -544.0
196099           Jun-68            2068-06-01                         -561.0
142623           Sep-59            2059-09-01                         -456.0
51136            May-67            2067-05-01                         -548.0
27171            Jun-64            2064-06-01                         -513.0
114952           Apr-65            2065-04-01                         -523.0
405178           Apr-64            2064-04-01                         -511.0
140819           Feb-67            2067-02-01                         -545.0
18335            Apr-64            2064-04-01                         -511.0
30788            Jan-68            2068-01-01                         -556.0
253133           May-62            2062-05-01                         -488.0
264977           Mar-68            2068-03-01                         -558.0
289852           Jan-62            2062-01-01                         -484.0
259941           Jan-66            2066-01-01                         -532.0
180632           Jul-64            2064-07-01                         -514.0
37117            Nov-66            2066-11-01                         -542.0
113270           Feb-67            2067-02-01                         -545.0
357903           Jan-67            2067-01-01                         -544.0

In [32]:
# As we can see; that the older dates years are calculated as 2060's and years after 1960's; which is ideally representing the 1960's years after 1960's.
# Hence; we will set the rows with the negative values to the maximum value to represent those very old years and dates

source_model_raw_train_feature_selection['months_since_earliest_cr_line'][source_model_raw_train_feature_selection['months_since_earliest_cr_line'] < 0] = source_model_raw_train_feature_selection['months_since_earliest_cr_line'].max()

print("Execution Completed")

<ipython-input-32-19e3f01bb704>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  source_model_raw_train_feature_selection['months_since_earliest_cr_line'][source_model_raw_train_feature_selection['months_since_earliest_cr_line'] < 0] = source_model_raw_train_feature_selection['months_since_earliest_cr_line'].max()

Execution Completed

In [33]:
# Displaying only the 3 columns w.r.t "earliest_cr_line" attribute and checking only the rows which has negative values after fixing the negative values

source_model_raw_train_feature_selection.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'months_since_earliest_cr_line']][source_model_raw_train_feature_selection['months_since_earliest_cr_line'] < 0]

Empty DataFrame
Columns: [earliest_cr_line, earliest_cr_line_date, months_since_earliest_cr_line]
Index: []

In [34]:
# Displaying the minimum value of the "months_since_earliest_cr_line" column 

min(source_model_raw_train_feature_selection['months_since_earliest_cr_line'])

73.0

In [35]:
# Displaying the maximum value of the "months_since_earliest_cr_line" column 

max(source_model_raw_train_feature_selection['months_since_earliest_cr_line'])

632.0

In [36]:
# Displaying a random sample of 20 rows of data and only the 3 columns w.r.t "earliest_cr_line" attribute

source_model_raw_train_feature_selection.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'months_since_earliest_cr_line']].sample(20)

       earliest_cr_line earliest_cr_line_date  months_since_earliest_cr_line
40568            Feb-99            1999-02-01                          271.0
364455           Oct-01            2001-10-01                          239.0
305608           May-01            2001-05-01                          244.0
193032           Sep-03            2003-09-01                          216.0
128095           Apr-02            2002-04-01                          233.0
28356            May-04            2004-05-01                          208.0
51427            Dec-00            2000-12-01                          249.0
367542           Nov-07            2007-11-01                          166.0
139219           Sep-93            1993-09-01                          336.0
336035           Jun-00            2000-06-01                          255.0
109589           Sep-00            2000-09-01                          252.0
361616           Dec-00            2000-12-01                          249.0
257776           Nov-92            1992-11-01                          346.0
196564           Feb-08            2008-02-01                          163.0
241794           Aug-97            1997-08-01                          289.0
403978           Aug-98            1998-08-01                          277.0
195204           Nov-10            2010-11-01                          130.0
145823           Jan-88            1988-01-01                          404.0
308580           Mar-00            2000-03-01                          258.0
243417           Feb-79            1979-02-01                          511.0

In [37]:
# Re-verifying the descriptive statistics of the values in the column "months_since_earliest_cr_line"; to ensure that there are no negative values

source_model_raw_train_feature_selection['months_since_earliest_cr_line'].describe()

count    419426.000000
mean        258.727330
std          93.966882
min          73.000000
25%         195.000000
50%         241.000000
75%         308.000000
max         632.000000
Name: months_since_earliest_cr_line, dtype: float64

In [38]:
# Verifying the data type of the "months_since_earliest_cr_line" column

source_model_raw_train_feature_selection['months_since_earliest_cr_line'].dtype

dtype('float64')

In [39]:
# Displaying a sample of 10 random data instances in the dataset with all the columns after pre-processing the string data type input feature "earliest_cr_line" (date type input feature) to numeric format

source_model_raw_train_feature_selection.sample(10)

,delinq_2yrs,mths_since_last_delinq,mths_since_last_record,pub_rec,total_rec_late_fee,recoveries,collection_recovery_fee,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,mths_since_recent_bc_dlq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,pub_rec_bankruptcies,revol_bal,revol_util,tot_cur_bal,total_bal_il,il_util,max_bal_bc,avg_cur_bal,num_rev_tl_bal_gt_0,percent_bc_gt_75,total_bal_ex_mort,earliest_cr_line,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,open_acc,total_acc,open_il_24m,open_rv_24m,mort_acc,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_sats,inq_last_6mths,inq_last_12m,acc_open_past_24mths,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mths_since_recent_bc,mths_since_recent_inq,num_tl_op_past_12m,open_il_12m,mths_since_rcnt_il,open_rv_12m,emp_length,home_ownership,annual_inc,dti,fico_score_status,earliest_cr_line_date,months_since_earliest_cr_line
23837,0.0,59.0,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,1.0,0.0,0.0,0.0,0.0,6168.0,25.1,95211.0,NaN,NaN,NaN,8656.0,5.0,0.0,42672.0,Jul-02,112.0,159.0,11.0,24.0,NaN,NaN,2.0,4.0,5.0,4.0,4.0,13.0,7.0,9.0,11.0,0.0,NaN,6.0,2.0,2.0,11.0,7.0,4.0,NaN,NaN,NaN,10+ years,MORTGAGE,32160.0,33.99,1,2002-07-01,230.0
202668,1.0,13.0,74.0,1.0,0.0,0.00,0.0000,0.0,0.0,0.0,13.0,13.0,0.0,0.0,0.0,0.0,1.0,10546.0,75.3,24987.0,14441.0,28.0,3587.0,2776.0,6.0,100.0,24987.0,Mar-07,62.0,78.0,9.0,14.0,0.0,1.0,1.0,2.0,6.0,2.0,5.0,4.0,6.0,9.0,9.0,0.0,0.0,1.0,21.0,21.0,45.0,NaN,0.0,0.0,42.0,0.0,10+ years,RENT,25000.0,64.52,1,2007-03-01,174.0
148638,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,15404.0,51.0,271912.0,0.0,NaN,7581.0,45319.0,4.0,0.0,15404.0,Apr-03,129.0,177.0,6.0,16.0,0.0,0.0,7.0,3.0,4.0,3.0,4.0,2.0,4.0,7.0,6.0,0.0,0.0,0.0,26.0,26.0,119.0,NaN,0.0,0.0,43.0,0.0,10+ years,MORTGAGE,75000.0,7.04,1,2003-04-01,221.0
216595,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,38015.0,68.2,220761.0,24349.0,83.0,20838.0,20069.0,3.0,50.0,62364.0,Mar-04,54.0,144.0,11.0,20.0,4.0,3.0,3.0,2.0,3.0,4.0,8.0,5.0,7.0,12.0,11.0,0.0,4.0,7.0,3.0,3.0,5.0,7.0,5.0,2.0,7.0,3.0,2 years,MORTGAGE,75000.0,20.75,1,2004-03-01,210.0
350561,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2387.0,18.9,80574.0,78187.0,118.0,1856.0,5372.0,2.0,0.0,80574.0,May-04,113.0,145.0,15.0,23.0,1.0,0.0,0.0,2.0,2.0,4.0,5.0,18.0,4.0,5.0,15.0,1.0,2.0,1.0,27.0,20.0,27.0,0.0,0.0,0.0,20.0,0.0,2 years,MORTGAGE,28800.0,15.04,0,2004-05-01,208.0
65748,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,17449.0,62.3,91325.0,35826.0,68.0,7923.0,7025.0,6.0,60.0,53275.0,Apr-07,121.0,83.0,13.0,22.0,2.0,3.0,3.0,4.0,6.0,5.0,6.0,10.0,8.0,9.0,13.0,0.0,2.0,5.0,8.0,8.0,8.0,8.0,2.0,0.0,18.0,2.0,9 years,MORTGAGE,62000.0,27.60,1,2007-04-01,173.0
60823,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,7833.0,77.6,7833.0,NaN,NaN,NaN,1306.0,6.0,66.7,7833.0,Aug-06,107.0,102.0,6.0,17.0,NaN,NaN,0.0,6.0,6.0,6.0,13.0,2.0,6.0,15.0,6.0,1.0,NaN,2.0,6.0,6.0,6.0,4.0,1.0,NaN,NaN,NaN,6 years,OWN,46000.0,7.57,1,2006-08-01,181.0
400433,2.0,6.0,79.0,2.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,6.0,0.0,0.0,0.0,0.0,0.0,11425.0,88.6,30140.0,17746.0,51.0,5346.0,4306.0,4.0,100.0,30140.0,Sep-96,247.0,154.0,7.0,12.0,0.0,1.0,0.0,2.0,4.0,2.0,2.0,6.0,4.0,5.0,7.0,0.0,1.0,2.0,24.0,16.0,27.0,11.0,0.0,0.0,25.0,0.0,10+ years,RENT,92000.0,13.67,0,1996-09-01,300.0
249877,3.0,11.0,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,26.0,13.0,0.0,0.0,0.0,0.0,0.0,17587.0,71.5,164543.0,NaN,NaN,NaN,9141.0,11.0,83.3,55418.0,Oct-95,115.0,234.0,18.0,35.0,NaN,NaN,5.0,6.0,11.0,6.0,13.0,10.0,11.0,20.0,18.0,0.0,NaN,2.0,10.0,10.0,19.0,17.0,1.0,NaN,NaN,NaN,10+ years,MORTGAGE,54000.0,32.78,1,1995-10-01,311.0
29506,0.0,38.0,NaN,0.0,0.0,1857.34,334.3212,0.0,0.0,0.0,39.0,38.0,7.0,0.0,0.0,0.0,0.0,6130.0,53.8,28568.0,NaN,NaN,NaN,2857.0,7.0,25.0,28568.0,Jan-00,125.0,182.0,11.0,35.0,NaN,NaN,0.0,4.0,7.0,5.0,12.0,6.0,10.0,29.0,11.0,0.0,NaN,7.0,8.0,8.0,16.0,13.0,1.0,NaN,NaN,NaN,10+ years,RENT,75000.0,22.89,0,2000-01-01,260.0

## 2. Pre-processing the String Data Type Input Feature "emp_length" to Numeric Format

In [40]:
# Extracting the unique values of the attribute "emp_length"

source_model_raw_train_feature_selection['emp_length'].unique()

array(['2 years', '< 1 year', '5 years', '10+ years', '7 years', '1 year',
       '4 years', '3 years', '8 years', nan, '9 years', '6 years'],
      dtype=object)

In [41]:
# Pre-processing the attribute "emp_length" and removing the strings from the numeric values; into a new column "emp_length_int"

source_model_raw_train_feature_selection['emp_length_int'] = source_model_raw_train_feature_selection['emp_length'].str.replace('\+ years', '')
source_model_raw_train_feature_selection['emp_length_int'] = source_model_raw_train_feature_selection['emp_length_int'].str.replace('< 1 year', str(0))
source_model_raw_train_feature_selection['emp_length_int'] = source_model_raw_train_feature_selection['emp_length_int'].str.replace(' years', '')
source_model_raw_train_feature_selection['emp_length_int'] = source_model_raw_train_feature_selection['emp_length_int'].str.replace(' year', '')

print("Execution Completed")

<ipython-input-41-e704f68235f9>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  source_model_raw_train_feature_selection['emp_length_int'] = source_model_raw_train_feature_selection['emp_length'].str.replace('\+ years', '')

Execution Completed

In [42]:
# Checking the datatype of the new pre-processed column named "emp_length_int"

type(source_model_raw_train_feature_selection['emp_length_int'][0])

str

In [43]:
# Converting the string type data into numeric datatype

source_model_raw_train_feature_selection['emp_length_int'] = pd.to_numeric(source_model_raw_train_feature_selection['emp_length_int'])

print("Execution Completed")

Execution Completed

In [44]:
# Displaying the pre-processed column "emp_length_int" for 10 random data instances

source_model_raw_train_feature_selection['emp_length_int'].sample(10)

258344     3.0
107040    10.0
40270      3.0
351552     7.0
112842     5.0
44651      0.0
80302     10.0
331039     0.0
206502     9.0
315233    10.0
Name: emp_length_int, dtype: float64

In [45]:
# Re-verifying the datatype of the new pre-processed column named "emp_length_int"

type(source_model_raw_train_feature_selection['emp_length_int'][0])

numpy.float64

In [46]:
# Displaying a sample of 10 random data instances in the dataset with all the columns after pre-processing the string data type input feature "emp_length" to numeric format

source_model_raw_train_feature_selection.sample(10)

,delinq_2yrs,mths_since_last_delinq,mths_since_last_record,pub_rec,total_rec_late_fee,recoveries,collection_recovery_fee,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,mths_since_recent_bc_dlq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,pub_rec_bankruptcies,revol_bal,revol_util,tot_cur_bal,total_bal_il,il_util,max_bal_bc,avg_cur_bal,num_rev_tl_bal_gt_0,percent_bc_gt_75,total_bal_ex_mort,earliest_cr_line,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,open_acc,total_acc,open_il_24m,open_rv_24m,mort_acc,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_sats,inq_last_6mths,inq_last_12m,acc_open_past_24mths,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mths_since_recent_bc,mths_since_recent_inq,num_tl_op_past_12m,open_il_12m,mths_since_rcnt_il,open_rv_12m,emp_length,home_ownership,annual_inc,dti,fico_score_status,earliest_cr_line_date,months_since_earliest_cr_line,emp_length_int
113038,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,24520.0,49.1,95206.0,NaN,NaN,NaN,5600.0,10.0,28.6,65525.0,Nov-00,111.0,174.0,17.0,41.0,NaN,NaN,2.0,7.0,10.0,7.0,10.0,22.0,12.0,17.0,17.0,1.0,NaN,12.0,6.0,6.0,12.0,6.0,4.0,NaN,NaN,NaN,7 years,MORTGAGE,49000.0,35.83,1,2000-11-01,250.0,7.0
256287,2.0,7.0,NaN,0.0,15.0,0.00,0.0000,0.0,0.0,0.0,7.0,7.0,1.0,0.0,0.0,0.0,0.0,1391.0,7.8,237048.0,114970.0,74.0,381.0,16932.0,3.0,0.0,116361.0,Jan-94,132.0,269.0,14.0,38.0,5.0,1.0,4.0,1.0,3.0,2.0,4.0,17.0,9.0,17.0,14.0,2.0,3.0,6.0,0.0,0.0,0.0,0.0,5.0,4.0,3.0,1.0,10+ years,MORTGAGE,180000.0,17.80,0,1994-01-01,332.0,10.0
36757,1.0,NaN,38.0,1.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,1.0,1.0,8324.0,81.0,53031.0,NaN,NaN,NaN,4821.0,9.0,75.0,53031.0,Jul-94,141.0,250.0,11.0,21.0,NaN,NaN,2.0,8.0,9.0,9.0,9.0,7.0,9.0,12.0,11.0,2.0,NaN,9.0,4.0,4.0,5.0,5.0,5.0,NaN,NaN,NaN,< 1 year,RENT,90000.0,18.64,0,1994-07-01,326.0,0.0
77120,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,6436.0,45.6,13096.0,6660.0,54.0,3280.0,2183.0,2.0,100.0,13096.0,Oct-98,239.0,191.0,6.0,10.0,0.0,3.0,0.0,2.0,2.0,2.0,3.0,4.0,5.0,6.0,6.0,0.0,1.0,3.0,7.0,7.0,75.0,0.0,2.0,0.0,30.0,2.0,3 years,OWN,78000.0,6.49,1,1998-10-01,275.0,3.0
297245,0.0,NaN,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,0.0,0.0,7676.0,57.0,18814.0,11138.0,87.0,5970.0,2090.0,5.0,100.0,18814.0,Jul-00,111.0,206.0,10.0,26.0,2.0,5.0,0.0,2.0,7.0,6.0,6.0,5.0,7.0,21.0,9.0,1.0,2.0,7.0,3.0,3.0,17.0,3.0,5.0,2.0,8.0,3.0,3 years,MORTGAGE,54200.0,11.05,1,2000-07-01,254.0,3.0
163223,0.0,37.0,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,666.0,7.0,24996.0,24330.0,80.0,453.0,3125.0,2.0,0.0,24996.0,Mar-90,340.0,130.0,8.0,15.0,1.0,2.0,0.0,2.0,2.0,3.0,4.0,8.0,6.0,7.0,8.0,0.0,0.0,3.0,22.0,8.0,22.0,23.0,1.0,1.0,8.0,0.0,10+ years,OWN,38000.0,25.81,1,1990-03-01,378.0,10.0
325445,0.0,57.0,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,62.0,62.0,1.0,0.0,0.0,0.0,0.0,28302.0,38.8,546729.0,133263.0,73.0,18979.0,30374.0,7.0,28.6,161565.0,May-98,155.0,229.0,20.0,36.0,3.0,11.0,3.0,5.0,7.0,7.0,9.0,11.0,15.0,22.0,20.0,0.0,3.0,14.0,6.0,6.0,17.0,7.0,5.0,2.0,7.0,3.0,6 years,MORTGAGE,124000.0,29.75,1,1998-05-01,280.0,6.0
273938,0.0,NaN,NaN,0.0,0.0,103.31,18.5958,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,4375.0,39.8,17103.0,NaN,NaN,NaN,1900.0,6.0,66.7,17103.0,Aug-88,319.0,35.0,9.0,19.0,NaN,NaN,0.0,3.0,6.0,3.0,3.0,10.0,7.0,9.0,9.0,2.0,NaN,5.0,4.0,4.0,4.0,0.0,2.0,NaN,NaN,NaN,NaN,RENT,15000.0,37.20,0,1988-08-01,397.0,NaN
220230,2.0,2.0,NaN,0.0,0.0,2442.96,439.7328,0.0,0.0,0.0,50.0,50.0,0.0,NaN,0.0,0.0,0.0,22253.0,64.0,222536.0,NaN,NaN,NaN,24726.0,5.0,50.0,49599.0,May-01,27.0,171.0,9.0,19.0,NaN,NaN,2.0,4.0,6.0,7.0,10.0,3.0,6.0,14.0,9.0,0.0,NaN,4.0,4.0,4.0,5.0,14.0,2.0,NaN,NaN,NaN,NaN,MORTGAGE,100000.0,19.60,0,2001-05-01,244.0,NaN
362911,0.0,64.0,NaN,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,16938.0,37.6,17746.0,808.0,5.0,8883.0,5915.0,2.0,0.0,17746.0,Sep-99,180.0,214.0,3.0,18.0,2.0,0.0,2.0,2.0,2.0,2.0,5.0,10.0,2.0,6.0,3.0,0.0,2.0,3.0,30.0,3.0,112.0,5.0,1.0,0.0,17.0,0.0,10+ years,MORTGAGE,85000.0,6.49,1,1999-09-01,264.0,10.0

## 3. Pre-processing the Categorical String Data Type Input Feature "home_ownership" to Numeric Format

In [47]:
# Extracting the unique values of the attribute "home_ownership"

source_model_raw_train_feature_selection['home_ownership'].unique()

array(['RENT', 'MORTGAGE', 'OWN', 'ANY'], dtype=object)

In [48]:
# Pre-processing the attribute "home_ownership" into a new column named "home_ownership_int"

source_model_raw_train_feature_selection['home_ownership_int'] = source_model_raw_train_feature_selection['home_ownership'].str.replace('OWN', '1')
source_model_raw_train_feature_selection['home_ownership_int'] = source_model_raw_train_feature_selection['home_ownership_int'].str.replace('MORTGAGE', '2')
source_model_raw_train_feature_selection['home_ownership_int'] = source_model_raw_train_feature_selection['home_ownership_int'].str.replace('RENT', '3')
source_model_raw_train_feature_selection['home_ownership_int'] = source_model_raw_train_feature_selection['home_ownership_int'].str.replace('ANY', '4')

print("Execution Completed")

Execution Completed

In [49]:
# Checking the datatype of the new pre-processed column named "home_ownership_int"

type(source_model_raw_train_feature_selection['home_ownership_int'][0])

str

In [50]:
# Converting the string type data into numeric datatype

source_model_raw_train_feature_selection['home_ownership_int'] = pd.to_numeric(source_model_raw_train_feature_selection['home_ownership_int'])

print("Execution Completed")

Execution Completed

In [51]:
# Re-verifying the datatype of the new pre-processed column named "home_ownership_int"

type(source_model_raw_train_feature_selection['home_ownership_int'][0])

numpy.int64

In [52]:
# Displaying a sample of 10 random data instances in the dataset with all the columns after pre-processing the categorical string data type input feature "home_ownership" to numeric format

source_model_raw_train_feature_selection.sample(10)

,delinq_2yrs,mths_since_last_delinq,mths_since_last_record,pub_rec,total_rec_late_fee,recoveries,collection_recovery_fee,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,mths_since_recent_bc_dlq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,pub_rec_bankruptcies,revol_bal,revol_util,tot_cur_bal,total_bal_il,il_util,max_bal_bc,avg_cur_bal,num_rev_tl_bal_gt_0,percent_bc_gt_75,total_bal_ex_mort,earliest_cr_line,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,open_acc,total_acc,open_il_24m,open_rv_24m,mort_acc,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_sats,inq_last_6mths,inq_last_12m,acc_open_past_24mths,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mths_since_recent_bc,mths_since_recent_inq,num_tl_op_past_12m,open_il_12m,mths_since_rcnt_il,open_rv_12m,emp_length,home_ownership,annual_inc,dti,fico_score_status,earliest_cr_line_date,months_since_earliest_cr_line,emp_length_int,home_ownership_int
122001,0.0,72.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.0,72.0,0.0,0.0,0.0,0.0,0.0,16419.0,36.7,17579.0,1160.0,11.0,6983.0,2197.0,5.0,50.0,17579.0,May-99,113.0,202.0,8.0,24.0,0.0,3.0,0.0,4.0,5.0,4.0,13.0,4.0,7.0,20.0,8.0,0.0,1.0,3.0,7.0,7.0,7.0,7.0,2.0,0.0,32.0,2.0,10+ years,RENT,72000.0,12.70,0,1999-05-01,268.0,10.0,3
31776,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,11602.0,46.6,18754.0,7152.0,81.0,4457.0,2344.0,6.0,40.0,18754.0,Jul-14,11.0,50.0,8.0,10.0,1.0,4.0,0.0,4.0,6.0,5.0,7.0,1.0,7.0,9.0,8.0,1.0,2.0,5.0,7.0,7.0,7.0,1.0,4.0,1.0,11.0,3.0,2 years,RENT,80000.0,6.66,1,2014-07-01,86.0,2.0,3
46408,2.0,11.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,13.0,1.0,0.0,0.0,0.0,0.0,13652.0,92.9,69569.0,10676.0,100.0,9652.0,17392.0,2.0,100.0,24328.0,Nov-94,174.0,284.0,4.0,11.0,1.0,0.0,2.0,1.0,2.0,1.0,4.0,3.0,2.0,6.0,4.0,0.0,0.0,1.0,160.0,5.0,169.0,NaN,1.0,1.0,5.0,0.0,2 years,MORTGAGE,43160.0,12.63,0,1994-11-01,322.0,2.0,2
210634,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,0.0,0.0,64753.0,84.0,338021.0,0.0,0.0,29718.0,37557.0,8.0,100.0,64753.0,Jul-89,159.0,348.0,9.0,19.0,0.0,1.0,7.0,6.0,8.0,7.0,7.0,2.0,8.0,12.0,9.0,0.0,1.0,2.0,22.0,6.0,22.0,6.0,1.0,0.0,100.0,0.0,9 years,MORTGAGE,84000.0,23.87,1,1989-07-01,386.0,9.0,2
291267,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,5212.0,85.4,44754.0,NaN,NaN,NaN,8951.0,2.0,100.0,44754.0,Dec-09,67.0,54.0,5.0,17.0,NaN,NaN,0.0,2.0,2.0,2.0,3.0,13.0,3.0,4.0,5.0,0.0,NaN,4.0,20.0,18.0,20.0,23.0,0.0,NaN,NaN,NaN,1 year,RENT,60000.0,15.24,1,2009-12-01,141.0,1.0,3
64589,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,27526.0,64.0,162848.0,NaN,NaN,NaN,7080.0,19.0,66.7,43076.0,Sep-05,54.0,119.0,23.0,34.0,NaN,NaN,1.0,12.0,19.0,12.0,18.0,5.0,20.0,28.0,23.0,0.0,NaN,4.0,10.0,10.0,10.0,10.0,2.0,NaN,NaN,NaN,10+ years,MORTGAGE,55000.0,33.67,1,2005-09-01,192.0,10.0,2
334777,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,26168.0,32.8,262128.0,18352.0,73.0,9539.0,15419.0,11.0,22.2,44520.0,Sep-07,122.0,130.0,17.0,29.0,2.0,2.0,1.0,7.0,11.0,9.0,11.0,8.0,15.0,20.0,17.0,0.0,0.0,4.0,6.0,6.0,6.0,13.0,1.0,0.0,13.0,1.0,10+ years,MORTGAGE,130000.0,12.68,1,2007-09-01,168.0,10.0,2
37054,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,19487.0,89.8,144542.0,7673.0,42.0,5423.0,10324.0,10.0,100.0,27160.0,Nov-01,89.0,185.0,14.0,18.0,0.0,5.0,1.0,4.0,10.0,4.0,5.0,5.0,10.0,12.0,14.0,0.0,1.0,5.0,8.0,8.0,9.0,11.0,3.0,0.0,26.0,3.0,10+ years,MORTGAGE,60000.0,26.04,0,2001-11-01,238.0,10.0,2
302007,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,0.0,0.0,7554.0,47.0,12215.0,NaN,NaN,NaN,1745.0,5.0,33.3,12215.0,Dec-95,141.0,230.0,7.0,26.0,NaN,NaN,6.0,3.0,6.0,4.0,9.0,3.0,6.0,18.0,7.0,0.0,NaN,2.0,5.0,5.0,37.0,8.0,2.0,NaN,NaN,NaN,8 years,OWN,136000.0,7.96,1,1995-12-01,309.0,8.0,1
306824,0.0,80.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80.0,80.0,1.0,0.0,0.0,0.0,0.0,1034.0,27.2,86098.0,NaN,NaN,NaN,10762.0,4.0,0.0,2714.0,Jun-07,94.0,90.0,8.0,13.0,NaN,NaN,1.0,2.0,4.0,3.0,4.0,4.0,6.0,7.0,8.0,0.0,NaN,8.0,0.0,0.0,0.0,8.0,4.0,NaN,NaN,NaN,2 years,MORTGAGE,120000.0,1.30,0,2007-06-01,171.0,2.0,2

In [53]:
# Re-verifying the datatypes of the dataframe after pre-processing all the string type features in to numeric format features in new attributes columns

for feat in source_model_raw_train_feature_selection.columns:
    print(feat, ".....", source_model_raw_train_feature_selection.dtypes[feat])

delinq_2yrs ..... float64
mths_since_last_delinq ..... float64
mths_since_last_record ..... float64
pub_rec ..... float64
total_rec_late_fee ..... float64
recoveries ..... float64
collection_recovery_fee ..... float64
acc_now_delinq ..... float64
chargeoff_within_12_mths ..... float64
delinq_amnt ..... float64
mths_since_recent_bc_dlq ..... float64
mths_since_recent_revol_delinq ..... float64
num_accts_ever_120_pd ..... float64
num_tl_120dpd_2m ..... float64
num_tl_30dpd ..... float64
num_tl_90g_dpd_24m ..... float64
pub_rec_bankruptcies ..... float64
revol_bal ..... float64
revol_util ..... float64
tot_cur_bal ..... float64
total_bal_il ..... float64
il_util ..... float64
max_bal_bc ..... float64
avg_cur_bal ..... float64
num_rev_tl_bal_gt_0 ..... float64
percent_bc_gt_75 ..... float64
total_bal_ex_mort ..... float64
earliest_cr_line ..... object
mo_sin_old_il_acct ..... float64
mo_sin_old_rev_tl_op ..... float64
open_acc ..... float64
total_acc ..... float64
open_il_24m ..... float64
open_rv_24m ..... float64
mort_acc ..... float64
num_actv_bc_tl ..... float64
num_actv_rev_tl ..... float64
num_bc_sats ..... float64
num_bc_tl ..... float64
num_il_tl ..... float64
num_op_rev_tl ..... float64
num_rev_accts ..... float64
num_sats ..... float64
inq_last_6mths ..... float64
inq_last_12m ..... float64
acc_open_past_24mths ..... float64
mo_sin_rcnt_rev_tl_op ..... float64
mo_sin_rcnt_tl ..... float64
mths_since_recent_bc ..... float64
mths_since_recent_inq ..... float64
num_tl_op_past_12m ..... float64
open_il_12m ..... float64
mths_since_rcnt_il ..... float64
open_rv_12m ..... float64
emp_length ..... object
home_ownership ..... object
annual_inc ..... float64
dti ..... float64
fico_score_status ..... int64
earliest_cr_line_date ..... datetime64[ns]
months_since_earliest_cr_line ..... float64
emp_length_int ..... float64
home_ownership_int ..... int64

## Handling Missing Values in all the Numeric Format Features/Columns to Support Implementation of the Feature Selection Method

In [54]:
# Checking the null "NaN" values (missing values) in the dataframe

pd.set_option('display.max_rows',None)
source_model_raw_train_feature_selection.isna().sum()

delinq_2yrs                            0
mths_since_last_delinq            210854
mths_since_last_record            349485
pub_rec                                0
total_rec_late_fee                     0
recoveries                             0
collection_recovery_fee                0
acc_now_delinq                         0
chargeoff_within_12_mths               0
delinq_amnt                            0
mths_since_recent_bc_dlq          319484
mths_since_recent_revol_delinq    276771
num_accts_ever_120_pd                  0
num_tl_120dpd_2m                   17834
num_tl_30dpd                           0
num_tl_90g_dpd_24m                     0
pub_rec_bankruptcies                   0
revol_bal                              0
revol_util                           297
tot_cur_bal                            0
total_bal_il                      159713
il_util                           197402
max_bal_bc                        159713
avg_cur_bal                           13
num_rev_tl_bal_gt_0                    0
percent_bc_gt_75                    4783
total_bal_ex_mort                      0
earliest_cr_line                       0
mo_sin_old_il_acct                 12883
mo_sin_old_rev_tl_op                   0
open_acc                               0
total_acc                              0
open_il_24m                       159713
open_rv_24m                       159713
mort_acc                               0
num_actv_bc_tl                         0
num_actv_rev_tl                        0
num_bc_sats                            0
num_bc_tl                              0
num_il_tl                              0
num_op_rev_tl                          0
num_rev_accts                          0
num_sats                               0
inq_last_6mths                         0
inq_last_12m                      159713
acc_open_past_24mths                   0
mo_sin_rcnt_rev_tl_op                  0
mo_sin_rcnt_tl                         0
mths_since_recent_bc                4422
mths_since_recent_inq              46830
num_tl_op_past_12m                     0
open_il_12m                       159713
mths_since_rcnt_il                167956
open_rv_12m                       159713
emp_length                         27892
home_ownership                         0
annual_inc                             0
dti                                  339
fico_score_status                      0
earliest_cr_line_date                  0
months_since_earliest_cr_line          0
emp_length_int                     27892
home_ownership_int                     0
dtype: int64

### After reviewing the missing values in the above listed 24 features/attributes/columns; it looks sensible to update the missing values with zero.
### This represents that a given feature i.e.; FICO score factor or Non-FICO score factor is not applicable for a given customer record/instance.

## 1. Handling Missing Values in the column named "mths_since_last_delinq"

In [55]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['mths_since_last_delinq'] = source_model_raw_train_feature_selection['mths_since_last_delinq'].fillna(0)

print("Execution Completed")

Execution Completed

## 2. Handling Missing Values in the column named "mths_since_last_record"

In [56]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['mths_since_last_record'] = source_model_raw_train_feature_selection['mths_since_last_record'].fillna(0)

print("Execution Completed")

Execution Completed

## 3. Handling Missing Values in the column named "mths_since_recent_bc_dlq"

In [57]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['mths_since_recent_bc_dlq'] = source_model_raw_train_feature_selection['mths_since_recent_bc_dlq'].fillna(0)

print("Execution Completed")

Execution Completed

## 4. Handling Missing Values in the column named "mths_since_recent_revol_delinq"

In [58]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['mths_since_recent_revol_delinq'] = source_model_raw_train_feature_selection['mths_since_recent_revol_delinq'].fillna(0)

print("Execution Completed")

Execution Completed

## 5. Handling Missing Values in the column named "num_tl_120dpd_2m"

In [59]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['num_tl_120dpd_2m'] = source_model_raw_train_feature_selection['num_tl_120dpd_2m'].fillna(0)

print("Execution Completed")

Execution Completed

## 6. Handling Missing Values in the column named "revol_util"

In [60]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['revol_util'] = source_model_raw_train_feature_selection['revol_util'].fillna(0)

print("Execution Completed")

Execution Completed

## 7. Handling Missing Values in the column named "total_bal_il"

In [61]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['total_bal_il'] = source_model_raw_train_feature_selection['total_bal_il'].fillna(0)

print("Execution Completed")

Execution Completed

## 8. Handling Missing Values in the column named "il_util"

In [62]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['il_util'] = source_model_raw_train_feature_selection['il_util'].fillna(0)

print("Execution Completed")

Execution Completed

## 9. Handling Missing Values in the column named "max_bal_bc"

In [63]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['max_bal_bc'] = source_model_raw_train_feature_selection['max_bal_bc'].fillna(0)

print("Execution Completed")

Execution Completed

## 10. Handling Missing Values in the column named "avg_cur_bal"

In [64]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['avg_cur_bal'] = source_model_raw_train_feature_selection['avg_cur_bal'].fillna(0)

print("Execution Completed")

Execution Completed

## 11. Handling Missing Values in the column named "percent_bc_gt_75"

In [65]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['percent_bc_gt_75'] = source_model_raw_train_feature_selection['percent_bc_gt_75'].fillna(0)

print("Execution Completed")

Execution Completed

## 12. Handling Missing Values in the column named "mo_sin_old_il_acct"

In [66]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['mo_sin_old_il_acct'] = source_model_raw_train_feature_selection['mo_sin_old_il_acct'].fillna(0)

print("Execution Completed")

Execution Completed

## 13. Handling Missing Values in the column named "mths_since_recent_bc"

In [67]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['mths_since_recent_bc'] = source_model_raw_train_feature_selection['mths_since_recent_bc'].fillna(0)

print("Execution Completed")

Execution Completed

## 14. Handling Missing Values in the column named "open_il_24m"

In [68]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['open_il_24m'] = source_model_raw_train_feature_selection['open_il_24m'].fillna(0)

print("Execution Completed")

Execution Completed

## 15. Handling Missing Values in the column named "open_rv_24m"

In [69]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['open_rv_24m'] = source_model_raw_train_feature_selection['open_rv_24m'].fillna(0)

print("Execution Completed")

Execution Completed

## 16. Handling Missing Values in the column named "inq_last_12m"

In [70]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['inq_last_12m'] = source_model_raw_train_feature_selection['inq_last_12m'].fillna(0)

print("Execution Completed")

Execution Completed

## 17. Handling Missing Values in the column named "mths_since_recent_inq"

In [71]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['mths_since_recent_inq'] = source_model_raw_train_feature_selection['mths_since_recent_inq'].fillna(0)

print("Execution Completed")

Execution Completed

## 18. Handling Missing Values in the column named "open_il_12m"

In [72]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['open_il_12m'] = source_model_raw_train_feature_selection['open_il_12m'].fillna(0)

print("Execution Completed")

Execution Completed

## 19. Handling Missing Values in the column named "mths_since_rcnt_il"

In [73]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['mths_since_rcnt_il'] = source_model_raw_train_feature_selection['mths_since_rcnt_il'].fillna(0)

print("Execution Completed")

Execution Completed

## 20. Handling Missing Values in the column named "open_rv_12m"

In [74]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['open_rv_12m'] = source_model_raw_train_feature_selection['open_rv_12m'].fillna(0)

print("Execution Completed")

Execution Completed

## 21. Handling Missing Values in the column named "emp_length"

In [75]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['emp_length'] = source_model_raw_train_feature_selection['emp_length'].fillna(0)

print("Execution Completed")

Execution Completed

## 22. Handling Missing Values in the column named "dti"

In [76]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['dti'] = source_model_raw_train_feature_selection['dti'].fillna(0)

print("Execution Completed")

Execution Completed

## 23. Handling Missing Values in the column named "emp_length_int"

In [77]:
# Filling all "NaN" values with zeros.

source_model_raw_train_feature_selection['emp_length_int'] = source_model_raw_train_feature_selection['emp_length_int'].fillna(0)

print("Execution Completed")

Execution Completed

## Re-Verification of the Missing Values in the Dataframe after fixing all the Missing Values in all the features/columns

In [78]:
# Re-checking the null "NaN" values (missing values) in the dataframe

pd.set_option('display.max_rows',None)
source_model_raw_train_feature_selection.isna().sum()

delinq_2yrs                       0
mths_since_last_delinq            0
mths_since_last_record            0
pub_rec                           0
total_rec_late_fee                0
recoveries                        0
collection_recovery_fee           0
acc_now_delinq                    0
chargeoff_within_12_mths          0
delinq_amnt                       0
mths_since_recent_bc_dlq          0
mths_since_recent_revol_delinq    0
num_accts_ever_120_pd             0
num_tl_120dpd_2m                  0
num_tl_30dpd                      0
num_tl_90g_dpd_24m                0
pub_rec_bankruptcies              0
revol_bal                         0
revol_util                        0
tot_cur_bal                       0
total_bal_il                      0
il_util                           0
max_bal_bc                        0
avg_cur_bal                       0
num_rev_tl_bal_gt_0               0
percent_bc_gt_75                  0
total_bal_ex_mort                 0
earliest_cr_line                  0
mo_sin_old_il_acct                0
mo_sin_old_rev_tl_op              0
open_acc                          0
total_acc                         0
open_il_24m                       0
open_rv_24m                       0
mort_acc                          0
num_actv_bc_tl                    0
num_actv_rev_tl                   0
num_bc_sats                       0
num_bc_tl                         0
num_il_tl                         0
num_op_rev_tl                     0
num_rev_accts                     0
num_sats                          0
inq_last_6mths                    0
inq_last_12m                      0
acc_open_past_24mths              0
mo_sin_rcnt_rev_tl_op             0
mo_sin_rcnt_tl                    0
mths_since_recent_bc              0
mths_since_recent_inq             0
num_tl_op_past_12m                0
open_il_12m                       0
mths_since_rcnt_il                0
open_rv_12m                       0
emp_length                        0
home_ownership                    0
annual_inc                        0
dti                               0
fico_score_status                 0
earliest_cr_line_date             0
months_since_earliest_cr_line     0
emp_length_int                    0
home_ownership_int                0
dtype: int64

## Saving the Source Model (SM) Raw Training Data with Initial Shortlisted Features Pre-processed into a csv file

In [170]:
# Exporting the Source Model (SM) Raw Training Data with Initial Shortlisted Features Pre-processed into a csv file

source_model_raw_train_feature_selection.to_csv("/Users/vidhyalakshmiparthasarathy/.CMVolumes/Google-Drive-pbvidhyauk6/QMUL_MSc_Project/credit_risk_scoring_project/data/source_model_feature_selection/source_model_raw_train_initial_features.csv")

print("Data Export Completed")

Data Export Completed

# IMPLEMENTING FEATURE SELECTION METHOD

## Creating a new updated list of all the features based on the 5 FICO factors and the Lenders Internal factors by replacing the actual feature names with the pre-processed feature names

### The 3 string data type actual features will be replaced with the pre-processed feature name for feature selection purposes.
> ### 1. Actual Feature "earliest_cr_line" will be replaced with the pre-processed feature "months_since_earliest_cr_line"
> ### 2. Actual Feature "emp_length" will be replaced with the pre-processed feature "emp_length_int"
> ### 3. Actual Feature "home_ownership" will be replaced with the pre-processed feature "home_ownership_int"

In [79]:
# Initial Shorlisted Featues List related to FICO Scores and Lender's Internal for the Source Model (SM)
# List Updated with the Pre-processed Feature Names Replacing the Actual Feature Names as applicable

sm_initial_shortlisted_features_list_modified = ['delinq_2yrs', 'mths_since_last_delinq', 'mths_since_last_record', 'pub_rec',
                                                'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 'acc_now_delinq',
                                                'chargeoff_within_12_mths', 'delinq_amnt', 'mths_since_recent_bc_dlq',
                                                'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_tl_120dpd_2m', 'num_tl_30dpd',
                                                'num_tl_90g_dpd_24m', 'pub_rec_bankruptcies',
                                                'revol_bal', 'revol_util', 'tot_cur_bal', 'total_bal_il', 'il_util', 'max_bal_bc', 'avg_cur_bal',
                                                'num_rev_tl_bal_gt_0', 'percent_bc_gt_75', 'total_bal_ex_mort',
                                                'months_since_earliest_cr_line', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op',
                                                'open_acc','total_acc', 'open_il_24m', 'open_rv_24m', 'mort_acc', 'num_actv_bc_tl', 'num_actv_rev_tl',
                                                'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_sats',
                                                'inq_last_6mths', 'inq_last_12m', 'acc_open_past_24mths', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
                                                'mths_since_recent_bc', 'mths_since_recent_inq', 'num_tl_op_past_12m', 'open_il_12m', 'mths_since_rcnt_il', 
                                                'open_rv_12m',
                                                'emp_length_int', 'home_ownership_int', 'annual_inc', 'dti',
                                                'fico_score_status']
                        
# Total Number of Initial Shortlisted Features
print("Total Number of Initial Shortlisted Features including the Target: ", len(sm_initial_shortlisted_features_list_modified))

print("Execution Completed")

Total Number of Initial Shortlisted Features including the Target:  59
Execution Completed

In [80]:
# List of features that are relevant to FICO Scores : "Payment History" Factor-1
# List Updated with the Pre-processed Feature Names Replacing the Actual Feature Names as applicable

sm_fico_payment_history_inputs_modified = ['delinq_2yrs', 'mths_since_last_delinq', 'mths_since_last_record', 'pub_rec', 'total_rec_late_fee',
                                          'recoveries', 'collection_recovery_fee', 'acc_now_delinq', 'chargeoff_within_12_mths', 'delinq_amnt',
                                          'mths_since_recent_bc_dlq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_tl_120dpd_2m',
                                          'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'pub_rec_bankruptcies']

sm_fico_payment_history_output_modified = ['fico_score_status']

sm_fico_payment_history_inputs_output_modified = ['delinq_2yrs', 'mths_since_last_delinq', 'mths_since_last_record', 'pub_rec', 'total_rec_late_fee',
                                                 'recoveries', 'collection_recovery_fee', 'acc_now_delinq', 'chargeoff_within_12_mths', 'delinq_amnt',
                                                 'mths_since_recent_bc_dlq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_tl_120dpd_2m',
                                                 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'pub_rec_bankruptcies', 'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 1 'Payment History': ", len(sm_fico_payment_history_inputs_modified))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 1 'Payment History':  17
Execution Completed

In [81]:
# List of features that are relevant to FICO Scores : "Amount Owed" Factor-2
# List Updated with the Pre-processed Feature Names Replacing the Actual Feature Names as applicable

sm_fico_amount_owed_inputs_modified = ['revol_bal', 'revol_util', 'tot_cur_bal', 'total_bal_il', 'il_util', 'max_bal_bc', 'avg_cur_bal',
                                      'num_rev_tl_bal_gt_0', 'percent_bc_gt_75', 'total_bal_ex_mort']

sm_fico_amount_owed_output_modified = ['fico_score_status']

sm_fico_amount_owed_inputs_output_modified = ['revol_bal', 'revol_util', 'tot_cur_bal', 'total_bal_il', 'il_util', 'max_bal_bc', 'avg_cur_bal',
                                             'num_rev_tl_bal_gt_0', 'percent_bc_gt_75', 'total_bal_ex_mort', 'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 2 'Amount Owed': ", len(sm_fico_amount_owed_inputs_modified))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 2 'Amount Owed':  10
Execution Completed

In [82]:
# List of features that are relevant to FICO Scores : "Length of Credit History" Factor-3
# List Updated with the Pre-processed Feature Names Replacing the Actual Feature Names as applicable

sm_fico_length_of_credit_history_inputs_modified = ['months_since_earliest_cr_line', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op']

sm_fico_length_of_credit_history_output_modified = ['fico_score_status']

sm_fico_length_of_credit_history_inputs_output_modified = ['months_since_earliest_cr_line', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 
                                                          'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 3 'Length of Credit History': ", len(sm_fico_length_of_credit_history_inputs_modified))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 3 'Length of Credit History':  3
Execution Completed

In [83]:
# List of features that are relevant to FICO Scores : "Credit Mix" Factor-4
# List Updated with the Pre-processed Feature Names Replacing the Actual Feature Names as applicable

sm_fico_credit_mix_inputs_modified = ['open_acc', 'total_acc', 'open_il_24m', 'open_rv_24m', 'mort_acc', 'num_actv_bc_tl', 'num_actv_rev_tl',
                                     'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_sats']

sm_fico_credit_mix_output_modified = ['fico_score_status']

sm_fico_credit_mix_inputs_output_modified = ['open_acc', 'total_acc', 'open_il_24m', 'open_rv_24m', 'mort_acc', 'num_actv_bc_tl', 'num_actv_rev_tl',
                                            'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_sats', 'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 4 'Credit Mix': ", len(sm_fico_credit_mix_inputs_modified))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 4 'Credit Mix':  13
Execution Completed

In [84]:
# List of features that are relevant to FICO Scores : "New Credit" Factor-5
# List Updated with the Pre-processed Feature Names Replacing the Actual Feature Names as applicable

sm_fico_new_credit_inputs_modified = ['inq_last_6mths', 'inq_last_12m', 'acc_open_past_24mths', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
                                     'mths_since_recent_bc', 'mths_since_recent_inq', 'num_tl_op_past_12m', 'open_il_12m', 'mths_since_rcnt_il', 'open_rv_12m']

sm_fico_new_credit_output_modified = ['fico_score_status']

sm_fico_new_credit_inputs_output_modified = ['inq_last_6mths', 'inq_last_12m', 'acc_open_past_24mths', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
                                            'mths_since_recent_bc', 'mths_since_recent_inq', 'num_tl_op_past_12m', 'open_il_12m', 'mths_since_rcnt_il', 
                                            'open_rv_12m', 'fico_score_status']

print("Total Number of Initial Shorlisted Features related to FICO Score Factor 5 'New Credit': ", len(sm_fico_new_credit_inputs_modified))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to FICO Score Factor 5 'New Credit':  11
Execution Completed

In [85]:
# List of features that are relevant to Non-FICO : "Lenders Internal" Factor 6
# List Updated with the Pre-processed Feature Names Replacing the Actual Feature Names as applicable

sm_non_fico_lenders_internal_inputs_modified = ['emp_length_int', 'home_ownership_int', 'annual_inc', 'dti']

sm_non_fico_lenders_internal_output_modified = ['fico_score_status']

sm_non_fico_lenders_internal_inputs_output_modified = ['emp_length_int', 'home_ownership_int', 'annual_inc', 'dti',
                                                      'fico_score_status']

print("Total Number of Initial Shorlisted Features related to Non-FICO Score Factor 6 'Lenders Internal': ", len(sm_non_fico_lenders_internal_inputs_modified))

print("Execution Completed")

Total Number of Initial Shorlisted Features related to Non-FICO Score Factor 6 'Lenders Internal':  4
Execution Completed

## Creating Individual Dataframes to include only the Unique Atributes with respect to 5 FICO Factors and Lenders Internal Factors

In [104]:
# Creating 2 dataframes for the inputs and the output respectively related to the FICO Factor 1 "Payment History"

sm_fico_1_X = source_model_raw_train_feature_selection.loc[:,sm_fico_payment_history_inputs_modified]
sm_fico_1_y = source_model_raw_train_feature_selection['fico_score_status']

print("Execution Completed")

Execution Completed

In [105]:
# Creating 2 dataframes for the inputs and the output respectively related to the FICO Factor 2 "Amount Owed"

sm_fico_2_X = source_model_raw_train_feature_selection.loc[:,sm_fico_amount_owed_inputs_modified]
sm_fico_2_y = source_model_raw_train_feature_selection['fico_score_status']

print("Execution Completed")

Execution Completed

In [106]:
# Creating 2 dataframes for the inputs and the output respectively related to the FICO Factor 3 "Length of Credit History"

sm_fico_3_X = source_model_raw_train_feature_selection.loc[:,sm_fico_length_of_credit_history_inputs_modified]
sm_fico_3_y = source_model_raw_train_feature_selection['fico_score_status']

print("Execution Completed")

Execution Completed

In [107]:
# Creating 2 dataframes for the inputs and the output respectively related to the FICO Factor 4 "Credit Mix"

sm_fico_4_X = source_model_raw_train_feature_selection.loc[:,sm_fico_credit_mix_inputs_modified]
sm_fico_4_y = source_model_raw_train_feature_selection['fico_score_status']

print("Execution Completed")

Execution Completed

In [108]:
# Creating 2 dataframes for the inputs and the output respectively related to the FICO Factor 5 "New Credit"

sm_fico_5_X = source_model_raw_train_feature_selection.loc[:,sm_fico_new_credit_inputs_modified]
sm_fico_5_y = source_model_raw_train_feature_selection['fico_score_status']

print("Execution Completed")

Execution Completed

In [109]:
# Creating 2 dataframes for the inputs and the output respectively related to Non-FICO Factor 6 - "Lenders Internal"

sm_non_fico_6_X = source_model_raw_train_feature_selection.loc[:,sm_non_fico_lenders_internal_inputs_modified]
sm_non_fico_6_y = source_model_raw_train_feature_selection['fico_score_status']

print("Execution Completed")

Execution Completed

# Feature Selection Method : Wrapper Method - Recursive Feature Elimination (RFE)

### In this Feature Selection Approach using Recursive Feature Elimination (RFE) Wrapper Method; we will be identifying the top most important features based on highest ranking for each of the 5 categories of FICO Score Factor and Lenders Internal Factor

## Importing Python Libraries for RFE

In [133]:
# Importing the Python Libraries

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

print("Import Completed")

Import Completed

## RFE for FICO Factor 1 - "Payment History"

## Creating dataframes for the inputs related to FICO Factor 1 "Payment History" and the output

In [134]:
# Verifying the type of Input and Output dataframes related to the FICO Factor 1 "Payment History"

print(type(sm_fico_1_X))
print(type(sm_fico_1_y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [135]:
# Verifying the shape of Input and Output dataframes related to the FICO Factor 1 "Payment History"

print(sm_fico_1_X.shape)
print(sm_fico_1_y.shape)

(419426, 17)
(419426,)

In [136]:
# Displaying sample data instances of the input dataframe which includes only the initial shortlisted inputs related to FICO Factor 1 "Payment History"

sm_fico_1_X[:5]

,delinq_2yrs,mths_since_last_delinq,mths_since_last_record,pub_rec,total_rec_late_fee,recoveries,collection_recovery_fee,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,mths_since_recent_bc_dlq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,pub_rec_bankruptcies
0,0.0,29.0,0.0,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,29.0,0.0,0.0,0.0,2614.41,470.5938,0.0,0.0,0.0,0.0,29.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,33.0,3.0,0.0,0.00,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
4,1.0,21.0,0.0,0.0,0.0,0.00,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [137]:
# Displaying sample data instances of the output dataframe with target named "fico_score_status"

sm_fico_1_y[:5]

0    1
1    1
2    0
3    0
4    0
Name: fico_score_status, dtype: int64

In [138]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 1 "Payment History"
# Selecting the top 6 features with rank 1

sm_rfe_fico_1_model_exe1 = LogisticRegression()
sm_rfe_fico_1_exe1 = RFE(sm_rfe_fico_1_model_exe1, 6)
sm_rfe_fico_1_fit_exe1 = sm_rfe_fico_1_exe1.fit(sm_fico_1_X, sm_fico_1_y)

print("FICO Factor 1 'Payment History' Total Selected Features: %s" % (sm_rfe_fico_1_fit_exe1.n_features_))
print("FICO Factor 1 'Payment History' Selected Features: %s" % (sm_rfe_fico_1_fit_exe1.support_))
print("FICO Factor 1 'Payment History' Selected Features Ranking: %s" % (sm_rfe_fico_1_fit_exe1.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=6 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 1 'Payment History' Total Selected Features: 6
FICO Factor 1 'Payment History' Selected Features: [ True False False  True False False False False False False False False
  True  True False  True  True]
FICO Factor 1 'Payment History' Selected Features Ranking: [ 1  6  8  1  4 11  5  2 10 12  7  9  1  1  3  1  1]

In [139]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 1 "Payment History"
# Selecting the top 5 features with rank 1

sm_rfe_fico_1_model_exe2 = LogisticRegression()
sm_rfe_fico_1_exe2 = RFE(sm_rfe_fico_1_model_exe2, 5)
sm_rfe_fico_1_fit_exe2 = sm_rfe_fico_1_exe2.fit(sm_fico_1_X, sm_fico_1_y)

print("FICO Factor 1 'Payment History' Total Selected Features: %s" % (sm_rfe_fico_1_fit_exe2.n_features_))
print("FICO Factor 1 'Payment History' Selected Features: %s" % (sm_rfe_fico_1_fit_exe2.support_))
print("FICO Factor 1 'Payment History' Selected Features Ranking: %s" % (sm_rfe_fico_1_fit_exe2.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=5 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 1 'Payment History' Total Selected Features: 5
FICO Factor 1 'Payment History' Selected Features: [ True False False  True False False False False False False False False
 False  True False  True  True]
FICO Factor 1 'Payment History' Selected Features Ranking: [ 1  7  9  1  5 12  6  3 11 13  8 10  2  1  4  1  1]

In [171]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 1 "Payment History"
# Features Ranked from 1 to 17

sm_rfe_fico_1_model_exe3 = LogisticRegression()
sm_rfe_fico_1_exe3 = RFE(sm_rfe_fico_1_model_exe3, 1)
sm_rfe_fico_1_fit_exe3 = sm_rfe_fico_1_exe3.fit(sm_fico_1_X, sm_fico_1_y)

print("FICO Factor 1 'Payment History' Total Selected Features: %s" % (sm_rfe_fico_1_fit_exe3.n_features_))
print("FICO Factor 1 'Payment History' Selected Features: %s" % (sm_rfe_fico_1_fit_exe3.support_))
print("FICO Factor 1 'Payment History' Selected Features Ranking: %s" % (sm_rfe_fico_1_fit_exe3.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 1 'Payment History' Total Selected Features: 1
FICO Factor 1 'Payment History' Selected Features: [False False False  True False False False False False False False False
 False False False False False]
FICO Factor 1 'Payment History' Selected Features Ranking: [ 2 11 13  1  9 16 10  7 15 17 12 14  6  3  8  5  4]

## RFE for FICO Factor 2 - "Amount Owed"

## Creating dataframes for the inputs related to FICO Factor 2 "Amount Owed" and the outputÂ¶

In [140]:
# Verifying the type of Input and Output dataframes related to the FICO Factor 2 "Amount Owed"

print(type(sm_fico_2_X))
print(type(sm_fico_2_y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [141]:
# Verifying the shape of Input and Output dataframes related to the FICO Factor 2 "Amount Owed"

print(sm_fico_2_X.shape)
print(sm_fico_2_y.shape)

(419426, 10)
(419426,)

In [142]:
# Displaying sample data instances of the input dataframe which includes only the initial shortlisted inputs related to FICO Factor 2 "Amount Owed"

sm_fico_2_X[:5]

,revol_bal,revol_util,tot_cur_bal,total_bal_il,il_util,max_bal_bc,avg_cur_bal,num_rev_tl_bal_gt_0,percent_bc_gt_75,total_bal_ex_mort
0,15694.0,20.8,166376.0,0.0,0.0,5692.0,9787.0,9.0,0.0,15694.0
1,27068.0,62.5,183276.0,0.0,0.0,19190.0,30546.0,4.0,33.3,27068.0
2,3191.0,41.4,25900.0,0.0,0.0,0.0,4317.0,2.0,100.0,25900.0
3,3770.0,73.9,16918.0,13148.0,47.0,2457.0,2417.0,5.0,50.0,16918.0
4,9088.0,80.4,179712.0,0.0,0.0,0.0,17971.0,4.0,66.7,104671.0

In [143]:
# Displaying sample data instances of the output dataframe with target named "fico_score_status"

sm_fico_2_y[:5]

0    1
1    1
2    0
3    0
4    0
Name: fico_score_status, dtype: int64

In [144]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 2 "Amount Owed"
# Selecting the top 5 features with rank 1

sm_rfe_fico_2_model_exe1 = LogisticRegression()
sm_rfe_fico_2_exe1 = RFE(sm_rfe_fico_2_model_exe1, 5)
sm_rfe_fico_2_fit_exe1 = sm_rfe_fico_2_exe1.fit(sm_fico_2_X, sm_fico_2_y)

print("FICO Factor 2 'Amount Owed' Total Selected Features: %s" % (sm_rfe_fico_2_fit_exe1.n_features_))
print("FICO Factor 2 'Amount Owed' Selected Features: %s" % (sm_rfe_fico_2_fit_exe1.support_))
print("FICO Factor 2 'Amount Owed' Selected Features Ranking: %s" % (sm_rfe_fico_2_fit_exe1.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=5 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 2 'Amount Owed' Total Selected Features: 5
FICO Factor 2 'Amount Owed' Selected Features: [False  True False False  True  True False  True  True False]
FICO Factor 2 'Amount Owed' Selected Features Ranking: [3 1 6 4 1 1 2 1 1 5]

In [145]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 2 "Amount Owed"
# Selecting the top 4 features with rank 1

sm_rfe_fico_2_model_exe2 = LogisticRegression()
sm_rfe_fico_2_exe2 = RFE(sm_rfe_fico_2_model_exe2, 4)
sm_rfe_fico_2_fit_exe2 = sm_rfe_fico_2_exe2.fit(sm_fico_2_X, sm_fico_2_y)

print("FICO Factor 2 'Amount Owed' Total Selected Features: %s" % (sm_rfe_fico_2_fit_exe2.n_features_))
print("FICO Factor 2 'Amount Owed' Selected Features: %s" % (sm_rfe_fico_2_fit_exe2.support_))
print("FICO Factor 2 'Amount Owed' Selected Features Ranking: %s" % (sm_rfe_fico_2_fit_exe2.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=4 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 2 'Amount Owed' Total Selected Features: 4
FICO Factor 2 'Amount Owed' Selected Features: [False  True False False  True False False  True  True False]
FICO Factor 2 'Amount Owed' Selected Features Ranking: [4 1 7 5 1 2 3 1 1 6]

In [173]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 2 "Amount Owed"
# Features Ranked from 1 to 10

sm_rfe_fico_2_model_exe3 = LogisticRegression()
sm_rfe_fico_2_exe3 = RFE(sm_rfe_fico_2_model_exe3, 1)
sm_rfe_fico_2_fit_exe3 = sm_rfe_fico_2_exe3.fit(sm_fico_2_X, sm_fico_2_y)

print("FICO Factor 2 'Amount Owed' Total Selected Features: %s" % (sm_rfe_fico_2_fit_exe3.n_features_))
print("FICO Factor 2 'Amount Owed' Selected Features: %s" % (sm_rfe_fico_2_fit_exe3.support_))
print("FICO Factor 2 'Amount Owed' Selected Features Ranking: %s" % (sm_rfe_fico_2_fit_exe3.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 2 'Amount Owed' Total Selected Features: 1
FICO Factor 2 'Amount Owed' Selected Features: [False False False False False False False  True False False]
FICO Factor 2 'Amount Owed' Selected Features Ranking: [ 7  3 10  8  4  5  6  1  2  9]

## RFE for FICO Factor 3 - "Length of Credit History"

## Creating dataframes for the inputs related to FICO Factor 3 "Length of Credit History" and the output

In [146]:
# Verifying the type of Input and Output dataframes related to the FICO Factor 3 "Length of Credit History"

print(type(sm_fico_3_X))
print(type(sm_fico_3_y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [147]:
# Verifying the shape of Input and Output dataframes related to the FICO Factor 3 "Length of Credit History"

print(sm_fico_3_X.shape)
print(sm_fico_3_y.shape)

(419426, 3)
(419426,)

In [148]:
# Displaying sample data instances of the input dataframe which includes only the initial shortlisted inputs related to FICO Factor 3 "Length of Credit History"

sm_fico_3_X[:5]

   months_since_earliest_cr_line  mo_sin_old_il_acct  mo_sin_old_rev_tl_op
0                          197.0               131.0                 120.0
1                          196.0               138.0                 158.0
2                          227.0               157.0                  89.0
3                          308.0               135.0                  26.0
4                          133.0                63.0                  39.0

In [149]:
# Displaying sample data instances of the output dataframe with target named "fico_score_status"

sm_fico_3_y[:5]

0    1
1    1
2    0
3    0
4    0
Name: fico_score_status, dtype: int64

In [150]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 3 "Length of Credit History"
# Selecting the top 2 features with rank 1

sm_rfe_fico_3_model_exe1 = LogisticRegression()
sm_rfe_fico_3_exe1 = RFE(sm_rfe_fico_3_model_exe1, 2)
sm_rfe_fico_3_fit_exe1 = sm_rfe_fico_3_exe1.fit(sm_fico_3_X, sm_fico_3_y)

print("FICO Factor 3 'Length of Credit History' Total Selected Features: %s" % (sm_rfe_fico_3_fit_exe1.n_features_))
print("FICO Factor 3 'Length of Credit History' Selected Features: %s" % (sm_rfe_fico_3_fit_exe1.support_))
print("FICO Factor 3 'Length of Credit History' Selected Features Ranking: %s" % (sm_rfe_fico_3_fit_exe1.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "

FICO Factor 3 'Length of Credit History' Total Selected Features: 2
FICO Factor 3 'Length of Credit History' Selected Features: [ True False  True]
FICO Factor 3 'Length of Credit History' Selected Features Ranking: [1 2 1]

In [151]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 3 "Length of Credit History"
# Selecting the top 1 feature with rank 1
# Features Ranked from 1 to 3

sm_rfe_fico_3_model_exe2 = LogisticRegression()
sm_rfe_fico_3_exe2 = RFE(sm_rfe_fico_3_model_exe2, 1)
sm_rfe_fico_3_fit_exe2 = sm_rfe_fico_3_exe2.fit(sm_fico_3_X, sm_fico_3_y)

print("FICO Factor 3 'Length of Credit History' Total Selected Features: %s" % (sm_rfe_fico_3_fit_exe2.n_features_))
print("FICO Factor 3 'Length of Credit History' Selected Features: %s" % (sm_rfe_fico_3_fit_exe2.support_))
print("FICO Factor 3 'Length of Credit History' Selected Features Ranking: %s" % (sm_rfe_fico_3_fit_exe2.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "

FICO Factor 3 'Length of Credit History' Total Selected Features: 1
FICO Factor 3 'Length of Credit History' Selected Features: [False False  True]
FICO Factor 3 'Length of Credit History' Selected Features Ranking: [2 3 1]

## RFE for FICO Factor 4 - "Credit Mix"

## Creating dataframes for the inputs related to FICO Factor 4 "Credit Mix" and the output

In [152]:
# Verifying the type of Input and Output dataframes related to the FICO Factor 4 "Credit Mix"

print(type(sm_fico_4_X))
print(type(sm_fico_4_y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [153]:
# Verifying the shape of Input and Output dataframes related to the FICO Factor 4 "Credit Mix"

print(sm_fico_4_X.shape)
print(sm_fico_4_y.shape)

(419426, 13)
(419426,)

In [154]:
# Displaying sample data instances of the input dataframe which includes only the initial shortlisted inputs related to FICO Factor 4 "Credit Mix"

sm_fico_4_X[:5]

,open_acc,total_acc,open_il_24m,open_rv_24m,mort_acc,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_sats
0,18.0,22.0,0.0,10.0,1.0,8.0,9.0,14.0,14.0,4.0,17.0,17.0,18.0
1,6.0,12.0,0.0,0.0,2.0,3.0,4.0,3.0,4.0,2.0,5.0,8.0,6.0
2,6.0,23.0,0.0,0.0,0.0,1.0,2.0,1.0,4.0,10.0,3.0,13.0,6.0
3,8.0,10.0,1.0,4.0,0.0,4.0,5.0,4.0,4.0,4.0,5.0,5.0,8.0
4,10.0,15.0,0.0,0.0,1.0,3.0,4.0,3.0,3.0,10.0,4.0,4.0,10.0

In [155]:
# Displaying sample data instances of the output dataframe with target named "fico_score_status"

sm_fico_4_y[:5]

0    1
1    1
2    0
3    0
4    0
Name: fico_score_status, dtype: int64

In [156]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 4 "Credit Mix"
# Selecting the top 3 features with rank 1

sm_rfe_fico_4_model_exe1 = LogisticRegression()
sm_rfe_fico_4_exe1 = RFE(sm_rfe_fico_4_model_exe1, 3)
sm_rfe_fico_4_fit_exe1 = sm_rfe_fico_4_exe1.fit(sm_fico_4_X, sm_fico_4_y)

print("FICO Factor 4 'Credit Mix' Total Selected Features: %s" % (sm_rfe_fico_4_fit_exe1.n_features_))
print("FICO Factor 4 'Credit Mix' Selected Features: %s" % (sm_rfe_fico_4_fit_exe1.support_))
print("FICO Factor 4 'Credit Mix' Selected Features Ranking: %s" % (sm_rfe_fico_4_fit_exe1.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 4 'Credit Mix' Total Selected Features: 3
FICO Factor 4 'Credit Mix' Selected Features: [ True False False False  True False False False False False False False
  True]
FICO Factor 4 'Credit Mix' Selected Features Ranking: [ 1  9  5  6  1  7  2  3 10 11  4  8  1]

In [157]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 4 "Credit Mix"
# Selecting the top 2 features with rank 1

sm_rfe_fico_4_model_exe2 = LogisticRegression()
sm_rfe_fico_4_exe2 = RFE(sm_rfe_fico_4_model_exe2, 2)
sm_rfe_fico_4_fit_exe2 = sm_rfe_fico_4_exe2.fit(sm_fico_4_X, sm_fico_4_y)

print("FICO Factor 4 'Credit Mix' Total Selected Features: %s" % (sm_rfe_fico_4_fit_exe2.n_features_))
print("FICO Factor 4 'Credit Mix' Selected Features: %s" % (sm_rfe_fico_4_fit_exe2.support_))
print("FICO Factor 4 'Credit Mix' Selected Features Ranking: %s" % (sm_rfe_fico_4_fit_exe2.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 4 'Credit Mix' Total Selected Features: 2
FICO Factor 4 'Credit Mix' Selected Features: [ True False False False False False False False False False False False
  True]
FICO Factor 4 'Credit Mix' Selected Features Ranking: [ 1 10  6  7  2  8  3  4 11 12  5  9  1]

In [174]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 4 "Credit Mix"
# Features Ranked from to 1 to 13

sm_rfe_fico_4_model_exe3 = LogisticRegression()
sm_rfe_fico_4_exe3 = RFE(sm_rfe_fico_4_model_exe3, 1)
sm_rfe_fico_4_fit_exe3 = sm_rfe_fico_4_exe3.fit(sm_fico_4_X, sm_fico_4_y)

print("FICO Factor 4 'Credit Mix' Total Selected Features: %s" % (sm_rfe_fico_4_fit_exe3.n_features_))
print("FICO Factor 4 'Credit Mix' Selected Features: %s" % (sm_rfe_fico_4_fit_exe3.support_))
print("FICO Factor 4 'Credit Mix' Selected Features Ranking: %s" % (sm_rfe_fico_4_fit_exe3.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 4 'Credit Mix' Total Selected Features: 1
FICO Factor 4 'Credit Mix' Selected Features: [ True False False False False False False False False False False False
 False]
FICO Factor 4 'Credit Mix' Selected Features Ranking: [ 1 11  7  8  3  9  4  5 12 13  6 10  2]

## RFE for FICO Factor 5 - "New Credit"

## Creating dataframes for the inputs related to FICO Factor 5 "New Credit" and the output

In [158]:
# Verifying the type of Input and Output dataframes related to the FICO Factor 5 "New Credit"

print(type(sm_fico_5_X))
print(type(sm_fico_5_y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [159]:
# Verifying the shape of Input and Output dataframes related to the FICO Factor 5 "New Credit"

print(sm_fico_5_X.shape)
print(sm_fico_5_y.shape)

(419426, 11)
(419426,)

In [160]:
# Displaying sample data instances of the input dataframe which includes only the initial shortlisted inputs related to FICO Factor 5 "New Credit"

sm_fico_5_X[:5]

,inq_last_6mths,inq_last_12m,acc_open_past_24mths,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mths_since_recent_bc,mths_since_recent_inq,num_tl_op_past_12m,open_il_12m,mths_since_rcnt_il,open_rv_12m
0,1.0,6.0,10.0,3.0,3.0,3.0,1.0,4.0,0.0,39.0,4.0
1,0.0,0.0,1.0,59.0,12.0,59.0,14.0,1.0,0.0,38.0,0.0
2,1.0,0.0,3.0,3.0,3.0,9.0,3.0,2.0,0.0,0.0,0.0
3,1.0,7.0,5.0,5.0,5.0,8.0,1.0,4.0,0.0,22.0,4.0
4,0.0,0.0,4.0,14.0,6.0,14.0,9.0,2.0,0.0,0.0,0.0

In [161]:
# Displaying sample data instances of the output dataframe with target named "fico_score_status"

sm_fico_5_y[:5]

0    1
1    1
2    0
3    0
4    0
Name: fico_score_status, dtype: int64

In [162]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 5 "New Credit"
# Selecting the top 3 features with rank 1

sm_rfe_fico_5_model_exe1 = LogisticRegression()
sm_rfe_fico_5_exe1 = RFE(sm_rfe_fico_5_model_exe1, 3)
sm_rfe_fico_5_fit_exe1 = sm_rfe_fico_5_exe1.fit(sm_fico_5_X, sm_fico_5_y)

print("FICO Factor 5 'New Credit' Total Selected Features: %s" % (sm_rfe_fico_5_fit_exe1.n_features_))
print("FICO Factor 5 'New Credit' Selected Features: %s" % (sm_rfe_fico_5_fit_exe1.support_))
print("FICO Factor 5 'New Credit' Selected Features Ranking: %s" % (sm_rfe_fico_5_fit_exe1.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 5 'New Credit' Total Selected Features: 3
FICO Factor 5 'New Credit' Selected Features: [ True False False False False False False  True  True False False]
FICO Factor 5 'New Credit' Selected Features Ranking: [1 4 3 5 7 9 8 1 1 6 2]

In [163]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 5 "New Credit"
# Selecting the top 2 features with rank 1

sm_rfe_fico_5_model_exe2 = LogisticRegression()
sm_rfe_fico_5_exe2 = RFE(sm_rfe_fico_5_model_exe2, 2)
sm_rfe_fico_5_fit_exe2 = sm_rfe_fico_5_exe2.fit(sm_fico_5_X, sm_fico_5_y)

print("FICO Factor 5 'New Credit' Total Selected Features: %s" % (sm_rfe_fico_5_fit_exe2.n_features_))
print("FICO Factor 5 'New Credit' Selected Features: %s" % (sm_rfe_fico_5_fit_exe2.support_))
print("FICO Factor 5 'New Credit' Selected Features Ranking: %s" % (sm_rfe_fico_5_fit_exe2.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 5 'New Credit' Total Selected Features: 2
FICO Factor 5 'New Credit' Selected Features: [ True False False False False False False False  True False False]
FICO Factor 5 'New Credit' Selected Features Ranking: [ 1  5  4  6  8 10  9  2  1  7  3]

In [175]:
# RFE with Logistic Regression for Feature Selection with respect to FICO Factor 5 "New Credit"
# Features Ranked from 1 to 11

sm_rfe_fico_5_model_exe3 = LogisticRegression()
sm_rfe_fico_5_exe3 = RFE(sm_rfe_fico_5_model_exe3, 1)
sm_rfe_fico_5_fit_exe3 = sm_rfe_fico_5_exe3.fit(sm_fico_5_X, sm_fico_5_y)

print("FICO Factor 5 'New Credit' Total Selected Features: %s" % (sm_rfe_fico_5_fit_exe3.n_features_))
print("FICO Factor 5 'New Credit' Selected Features: %s" % (sm_rfe_fico_5_fit_exe3.support_))
print("FICO Factor 5 'New Credit' Selected Features Ranking: %s" % (sm_rfe_fico_5_fit_exe3.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

FICO Factor 5 'New Credit' Total Selected Features: 1
FICO Factor 5 'New Credit' Selected Features: [ True False False False False False False False False False False]
FICO Factor 5 'New Credit' Selected Features Ranking: [ 1  6  5  7  9 11 10  3  2  8  4]

## RFE for Non-FICO Factor 6 - "Lenders Internal

## Creating dataframes for the inputs related to Non-FICO Factor 6 - "Lenders Internal" and the output

In [164]:
# Verifying the type of Input and Output dataframes related to Non-FICO Factor 6 - "Lenders Internal"

print(type(sm_non_fico_6_X))
print(type(sm_non_fico_6_y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [165]:
# Verifying the shape of Input and Output dataframes related to Non-FICO Factor 6 - "Lenders Internal"

print(sm_non_fico_6_X.shape)
print(sm_non_fico_6_y.shape)

(419426, 4)
(419426,)

In [166]:
# Displaying sample data instances of the input dataframe which includes only the initial shortlisted inputs related to Non-FICO Factor 6 - "Lenders Internal"

sm_non_fico_6_X[:5]

   emp_length_int  home_ownership_int  annual_inc    dti
0             2.0                   3     60000.0   9.54
1             0.0                   2     60000.0  11.38
2             0.0                   3     65000.0  26.97
3             2.0                   3     57000.0  11.94
4             5.0                   2    100000.0  31.48

In [167]:
# Displaying sample data instances of the output dataframe with target named "fico_score_status"

sm_non_fico_6_y[:5]

0    1
1    1
2    0
3    0
4    0
Name: fico_score_status, dtype: int64

In [168]:
# RFE with Logistic Regression for Feature Selection with respect to Non-FICO Factor 6 - "Lenders Internal"
# Selecting the top 3 features with rank 1

sm_rfe_non_fico_6_model_exe1 = LogisticRegression()
sm_rfe_non_fico_6_exe1 = RFE(sm_rfe_non_fico_6_model_exe1, 3)
sm_rfe_non_fico_6_fit_exe1 = sm_rfe_non_fico_6_exe1.fit(sm_non_fico_6_X, sm_non_fico_6_y)

print("Non-FICO Factor 6 'Lenders Internal' Total Selected Features: %s" % (sm_rfe_non_fico_6_fit_exe1.n_features_))
print("Non-FICO Factor 6 'Lenders Internal' Selected Features: %s" % (sm_rfe_non_fico_6_fit_exe1.support_))
print("Non-FICO Factor 6 'Lenders Internal' Selected Features Ranking: %s" % (sm_rfe_non_fico_6_fit_exe1.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "

Non-FICO Factor 6 'Lenders Internal' Total Selected Features: 3
Non-FICO Factor 6 'Lenders Internal' Selected Features: [ True False  True  True]
Non-FICO Factor 6 'Lenders Internal' Selected Features Ranking: [1 2 1 1]

In [169]:
# RFE with Logistic Regression for Feature Selection with respect to Non-FICO Factor 6 - "Lenders Internal"
# Selecting the top 2 features with rank 1

sm_rfe_non_fico_6_model_exe2 = LogisticRegression()
sm_rfe_non_fico_6_exe2 = RFE(sm_rfe_non_fico_6_model_exe2, 2)
sm_rfe_non_fico_6_fit_exe2 = sm_rfe_non_fico_6_exe2.fit(sm_non_fico_6_X, sm_non_fico_6_y)

print("Non-FICO Factor 6 'Lenders Internal' Total Selected Features: %s" % (sm_rfe_non_fico_6_fit_exe2.n_features_))
print("Non-FICO Factor 6 'Lenders Internal' Selected Features: %s" % (sm_rfe_non_fico_6_fit_exe2.support_))
print("Non-FICO Factor 6 'Lenders Internal' Selected Features Ranking: %s" % (sm_rfe_non_fico_6_fit_exe2.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "

Non-FICO Factor 6 'Lenders Internal' Total Selected Features: 2
Non-FICO Factor 6 'Lenders Internal' Selected Features: [False False  True  True]
Non-FICO Factor 6 'Lenders Internal' Selected Features Ranking: [2 3 1 1]

In [177]:
# RFE with Logistic Regression for Feature Selection with respect to Non-FICO Factor 6 - "Lenders Internal"
# Features Ranked from 1 to 4

sm_rfe_non_fico_6_model_exe3 = LogisticRegression()
sm_rfe_non_fico_6_exe3 = RFE(sm_rfe_non_fico_6_model_exe3, 1)
sm_rfe_non_fico_6_fit_exe3 = sm_rfe_non_fico_6_exe3.fit(sm_non_fico_6_X, sm_non_fico_6_y)

print("Non-FICO Factor 6 'Lenders Internal' Total Selected Features: %s" % (sm_rfe_non_fico_6_fit_exe3.n_features_))
print("Non-FICO Factor 6 'Lenders Internal' Selected Features: %s" % (sm_rfe_non_fico_6_fit_exe3.support_))
print("Non-FICO Factor 6 'Lenders Internal' Selected Features Ranking: %s" % (sm_rfe_non_fico_6_fit_exe3.ranking_))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "

Non-FICO Factor 6 'Lenders Internal' Total Selected Features: 1
Non-FICO Factor 6 'Lenders Internal' Selected Features: [False False  True False]
Non-FICO Factor 6 'Lenders Internal' Selected Features Ranking: [3 4 1 2]

## SOURCE MODEL (SM) TRANING DATA : FINALISED FEATURES

### Based on the above results from "Recursive Feature Elimination" Wrapper Method for Feature Selection; we will be selecting the top ranked features for each of the 5 FICO factors and Non-FICO factor with below listed percentages.

### The percentages of top ranked features from each factor are selected by considering the effect of feature importance/weightage given by the official FICO website for the 5 FICO factors and custom feature importance/weightage that can potentially be considered by the lenders for the non-FICO factor

> #### 1. FICO Factor 1      - Payment History            - (35%)      <b><font color='blue'>- 50% of Top-Ranked Features</b></font>      <b><font color='green'>- 9 out of 17</b></font>
> #### 2. FICO Factor 2      - Amount Owed                - (30%)      <b><font color='blue'>- 50% of Top-Ranked Features</b></font>      <b><font color='green'>- 5 out of 10</b></font>
> #### 3. FICO Factor 3      - Length of Credit History   - (15%)      <b><font color='blue'>- 50% of Top-Ranked Features</b></font>      <b><font color='green'>- 2 out of 3</b></font>
> #### 4. FICO Factor 4      - Credit Mix                 - (10%)      <b><font color='blue'>- 25% of Top-Ranked Features</b></font>      <b><font color='green'>- 3 out of 13</b></font>
> #### 5. FICO Factor 5      - New Credit                 - (10%)      <b><font color='blue'>- 25% of Top-Ranked Features</b></font>      <b><font color='green'>- 3 out of 10</b></font>
> #### 6. Non-FICO Factor 6  - Lender's Internal          - (Custom)   <b><font color='blue'>- 75% of Top-Ranked Features</b></font>      <b><font color='green'>- 3 out of 4</b></font>

### This results in a total of about <b><font color='yellow'>25 Input Features and 1 Target/Output</b></font>

## Finalised List of 25 Features Based on Each of the 5 FICO Factor and Non-FICO Lenders Internal Factor; along with 1 Target

In [183]:
# Finalised Features List (25) related to FICO Scores and Lender's Internal for the Source Model (SM) with 1 Output (Target)
# Listed in the order of the 5 FICO Factor and 1 Non-FICO Factor
# Listed in the increasing order of the ranking starting from 1 for each of the 5 FICO Factor and 1 Non-FICO Factor

sm_finalised_features_list = ['pub_rec', 'delinq_2yrs', 'num_tl_120dpd_2m', 'pub_rec_bankruptcies', 'num_tl_90g_dpd_24m',
                             'num_accts_ever_120_pd', 'acc_now_delinq', 'num_tl_30dpd', 'total_rec_late_fee',
                             'num_rev_tl_bal_gt_0', 'percent_bc_gt_75', 'revol_util', 'il_util', 'max_bal_bc',
                             'mo_sin_old_rev_tl_op', 'earliest_cr_line',
                             'open_acc', 'num_sats', 'mort_acc',
                             'inq_last_6mths', 'open_il_12m', 'num_tl_op_past_12m',
                             'annual_inc', 'dti', 'emp_length',
                             'fico_score_status']
                        
# Total Number of Finalised Features
print("Total Number of Finalised Features including 1 Target: ", len(sm_finalised_features_list))

print("Execution Completed")

Total Number of Finalised Features including 1 Target:  26
Execution Completed

In [184]:
# Finalised Features List (9) that are relevant to FICO Scores : "Payment History" Factor-1
# Listed in the increasing order of the ranking starting from 1 to 9

sm_fico_payment_history_finalised_features = ['pub_rec', 'delinq_2yrs', 'num_tl_120dpd_2m', 'pub_rec_bankruptcies', 'num_tl_90g_dpd_24m',
                                             'num_accts_ever_120_pd', 'acc_now_delinq', 'num_tl_30dpd', 'total_rec_late_fee']
                                             
print("Total Number of Finalised Features related to FICO Score Factor 1 'Payment History': ", len(sm_fico_payment_history_finalised_features))

print("Execution Completed")

Total Number of Finalised Features related to FICO Score Factor 1 'Payment History':  9
Execution Completed

In [185]:
# Finalised Features List (5) that are relevant to FICO Scores : "Amount Owed" Factor-2
# Listed in the increasing order of the ranking starting from 1 to 5

sm_fico_amount_owed_finalised_features = ['num_rev_tl_bal_gt_0', 'percent_bc_gt_75', 'revol_util', 'il_util', 'max_bal_bc']                                        

print("Total Number of Finalised Features related to FICO Score Factor 2 'Amount Owed': ", len(sm_fico_amount_owed_finalised_features))

print("Execution Completed")

Total Number of Finalised Features related to FICO Score Factor 2 'Amount Owed':  5
Execution Completed

In [186]:
# Finalised Features List (2) that are relevant to FICO Scores : "Length of Credit History"
# Listed in the increasing order of the ranking starting from 1 to 2

sm_fico_length_of_credit_history_finalised_features = ['mo_sin_old_rev_tl_op', 'earliest_cr_line']                                                   
                             
print("Total Number of Finalised Features related to FICO Score Factor 3 'Length of Credit History': ", len(sm_fico_length_of_credit_history_finalised_features))

print("Execution Completed")

Total Number of Finalised Features related to FICO Score Factor 3 'Length of Credit History':  2
Execution Completed

In [187]:
# Finalised Features List (3) that are relevant to FICO Scores : "Credit Mix" Factor-4
# Listed in the increasing order of the ranking starting from 1 to 3

sm_fico_credit_mix_finalised_features = ['open_acc', 'num_sats', 'mort_acc']                                       

print("Total Number of Finalised Features related to FICO Score Factor 4 'Credit Mix': ", len(sm_fico_credit_mix_finalised_features))

print("Execution Completed")

Total Number of Finalised Features related to FICO Score Factor 4 'Credit Mix':  3
Execution Completed

In [188]:
# Finalised Features List (3) that are relevant to FICO Scores : "New Credit" Factor-5
# Listed in the increasing order of the ranking starting from 1 to 3

sm_fico_new_credit_finalised_features = ['inq_last_6mths', 'open_il_12m', 'num_tl_op_past_12m']                                        
                           
print("Total Number of Finalised Features related to FICO Score Factor 5 'New Credit': ", len(sm_fico_new_credit_finalised_features))

print("Execution Completed")

Total Number of Finalised Features related to FICO Score Factor 5 'New Credit':  3
Execution Completed

In [189]:
# Finalised Features List (3) that are relevant to Non-FICO : "Lenders Internal" Factor 6
# Listed in the increasing order of the ranking starting from 1 to 3

sm_non_fico_lenders_internal_finalised_features = ['annual_inc', 'dti', 'emp_length']
                                                                               
print("Total Number of Finalised Features related to Non-FICO Score Factor 6 'Lenders Internal': ", len(sm_non_fico_lenders_internal_finalised_features))

print("Execution Completed")

Total Number of Finalised Features related to Non-FICO Score Factor 6 'Lenders Internal':  3
Execution Completed