# EVALUATING THE TARGET MODEL 2 (BINARY CLASSIFICATION) ON THE VALIDATION DATA : SCENARIO-1

## Scenario-1 : Source Model is used as a Feature Extractor by the Target Model 2 (TM2) for the Binary Classification of "credit_default" or "default_risk"

## Importing Python Libraries

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

print("Import Completed")

Import Completed

## Importing the Target Model 2 (TM2) Scenario-1 Validation Data csv Files

In [2]:
# Importing the Target Model 2 (TM2) Scenario-1 Validation Data Input csv File

tm2_validation_X = pd.read_csv("/Users/vidhyalakshmiparthasarathy/.CMVolumes/Google-Drive-pbvidhyauk6/QMUL_MSc_Project/credit_risk_scoring_project/data/target_model_final_data/tm_validation_final_input_X.csv")

print("Data Export Completed")

Data Export Completed

In [3]:
# Importing the Target Model 2 (TM2) Scenario-1 Validation Data Output csv File

tm2_validation_y = pd.read_csv("/Users/vidhyalakshmiparthasarathy/.CMVolumes/Google-Drive-pbvidhyauk6/QMUL_MSc_Project/credit_risk_scoring_project/data/target_model_final_data/tm_validation_final_output_y_clas.csv")

print("Data Export Completed")

Data Export Completed

## Target Model 2 (TM2) Scenario-1 Validation Input Data Exploration

In [4]:
# Sets the pandas dataframe options to display all columns/ rows.

pd.options.display.max_columns = None
#pd.options.display.max_rows = None

print("Execution Completed")

Execution Completed

In [5]:
# Checking the size of the dataset

tm2_validation_X.shape

(83885, 75)

In [6]:
# Checking the first 3 column names of the dataset

tm2_validation_X.columns[[0, 1, 2]]

Index(['Unnamed: 0', 'pub_rec:0', 'pub_record:non_zero'], dtype='object')

In [7]:
# Removing the first index column from the dataset

tm2_validation_X.drop(tm2_validation_X.columns[0], axis = 1, inplace = True)

print("Execution Completed")

Execution Completed

In [8]:
# Re-checking the size of the dataset after removing the index column

tm2_validation_X.shape

(83885, 74)

In [9]:
# Displying the first 5 data instances of the dataframe

tm2_validation_X.head()

,pub_rec:0,pub_record:non_zero,delinq_2yrs:0,delinq_2yrs:1,delinq_2yrs:greater_than_1,num_tl_120dpd_2m:0,num_tl_120dpd_2m:non_zero,pub_rec_bankruptcies:0,pub_rec_bankruptcies:non_zero,num_tl_90g_dpd_24m:0,num_tl_90g_dpd_24m:non_zero,num_accts_ever_120_pd:0,num_accts_ever_120_pd:_non_zero,acc_now_delinq:0,acc_now_delinq:non_zero,num_tl_30dpd:0,num_tl_30dpd:non_zero,total_rec_late_fee:0,total_rec_late_fee:non_zero,num_rev_tl_bal_gt_0:0,num_rev_tl_bal_gt_0:1_to_5,num_rev_tl_bal_gt_0:greater_than_5,percent_bc_gt_75:0,percent_bc_gt_75:1_to_75,percent_bc_gt_75:greater_than_75,revol_util:0_to_15,revol_util:16_to_30,revol_util:31_to_60,revol_util:greater_than_60,il_util:0,il_util:1_to_100,il_util:greater_than_100,max_bal_bc:0_to_2500,max_bal_bc:2501_to_5000,max_bal_bc:5001_to_10000,max_bal_bc:greater_than_10000,mo_sin_old_rev_tl_op:less_than_24months,mo_sin_old_rev_tl_op:25months_to_60months,mo_sin_old_rev_tl_op:greater_than_60months,months_since_earliest_cr_line:less_than_120months,months_since_earliest_cr_line:121months_to_240months,months_since_earliest_cr_line:greater_than_240months,open_acc:less_than_5,open_acc:6_to_8,open_acc:greater_than_8,num_sats:0_to_5,num_sats:6_to_8,num_sats:greater_than_8,mort_acc:0,mort_acc:1_to_3,mort_acc:greater_than_3,inq_last_6mths:0,inq_last_6mths:1,inq_last_6mths:greater_than_1,open_il_12m:_0,open_il_12m:_1,open_il_12m:greater_than_1,num_tl_op_past_12m:0,num_tl_op_past_12m:1,num_tl_op_past_12m:2,num_tl_op_past_12m:3,num_tl_op_past_12m:greater_than_3,annual_inc:0_to_25000,annual_inc:25001_to_50000,annual_inc:50001_to_75000,annual_inc:75001_to_100000,annual_inc:greater_than_100001,dti:0_to_36,dti:greater_than_36,emp_length_int:less_than_0,emp_length_int:1_to_2,emp_length_int:3_to_5,emp_length_int:6_to_9,emp_length_int:greater_than_9
0,0,1,1,0,0,1,0,1,0,1,0,0,1,1,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1
1,1,0,1,0,0,1,0,1,0,1,0,0,1,1,0,1,0,1,0,0,1,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0
2,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0
3,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1
4,1,0,1,0,0,1,0,1,0,1,0,0,1,1,0,1,0,1,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,1,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0

In [10]:
# Displying the last 5 data instances of the dataframe

tm2_validation_X.tail()

,pub_rec:0,pub_record:non_zero,delinq_2yrs:0,delinq_2yrs:1,delinq_2yrs:greater_than_1,num_tl_120dpd_2m:0,num_tl_120dpd_2m:non_zero,pub_rec_bankruptcies:0,pub_rec_bankruptcies:non_zero,num_tl_90g_dpd_24m:0,num_tl_90g_dpd_24m:non_zero,num_accts_ever_120_pd:0,num_accts_ever_120_pd:_non_zero,acc_now_delinq:0,acc_now_delinq:non_zero,num_tl_30dpd:0,num_tl_30dpd:non_zero,total_rec_late_fee:0,total_rec_late_fee:non_zero,num_rev_tl_bal_gt_0:0,num_rev_tl_bal_gt_0:1_to_5,num_rev_tl_bal_gt_0:greater_than_5,percent_bc_gt_75:0,percent_bc_gt_75:1_to_75,percent_bc_gt_75:greater_than_75,revol_util:0_to_15,revol_util:16_to_30,revol_util:31_to_60,revol_util:greater_than_60,il_util:0,il_util:1_to_100,il_util:greater_than_100,max_bal_bc:0_to_2500,max_bal_bc:2501_to_5000,max_bal_bc:5001_to_10000,max_bal_bc:greater_than_10000,mo_sin_old_rev_tl_op:less_than_24months,mo_sin_old_rev_tl_op:25months_to_60months,mo_sin_old_rev_tl_op:greater_than_60months,months_since_earliest_cr_line:less_than_120months,months_since_earliest_cr_line:121months_to_240months,months_since_earliest_cr_line:greater_than_240months,open_acc:less_than_5,open_acc:6_to_8,open_acc:greater_than_8,num_sats:0_to_5,num_sats:6_to_8,num_sats:greater_than_8,mort_acc:0,mort_acc:1_to_3,mort_acc:greater_than_3,inq_last_6mths:0,inq_last_6mths:1,inq_last_6mths:greater_than_1,open_il_12m:_0,open_il_12m:_1,open_il_12m:greater_than_1,num_tl_op_past_12m:0,num_tl_op_past_12m:1,num_tl_op_past_12m:2,num_tl_op_past_12m:3,num_tl_op_past_12m:greater_than_3,annual_inc:0_to_25000,annual_inc:25001_to_50000,annual_inc:50001_to_75000,annual_inc:75001_to_100000,annual_inc:greater_than_100001,dti:0_to_36,dti:greater_than_36,emp_length_int:less_than_0,emp_length_int:1_to_2,emp_length_int:3_to_5,emp_length_int:6_to_9,emp_length_int:greater_than_9
83880,1,0,1,0,0,1,0,1,0,1,0,0,1,1,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0
83881,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1
83882,0,1,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1
83883,1,0,0,1,0,1,0,1,0,0,1,0,1,1,0,1,0,1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1
83884,0,1,1,0,0,1,0,0,1,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1

## Target Model 2 (TM2) Scenario-1 Validation Output Data Exploration

In [11]:
# Sets the pandas dataframe options to display all columns/ rows.

pd.options.display.max_columns = None
#pd.options.display.max_rows = None

print("Execution Completed")

Execution Completed

In [16]:
# Checking the size of the dataset

tm2_validation_y.shape

(83885, 1)

In [17]:
# Checking the first 2 column names of the dataset

tm2_validation_y.columns[[0]]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [14]:
# Removing the first index column from the dataset

tm2_validation_y.drop(tm2_validation_y.columns[0], axis = 1, inplace = True)

print("Execution Completed")

Execution Completed

In [15]:
# Re-checking the size of the dataset after removing the index column

tm2_validation_y.shape

(83885, 1)

In [ ]:
# Displying the first 5 data instances of the dataframe

tm2_validation_y.head()

In [ ]:
# Displying the last 5 data instances of the dataframe

tm2_validation_y.tail()

## Loading the Pre-Trained Target Model 2 (TM2) for Classification Evaluation of "credit_default" as per Scenario-1

### Target Model 2 (TM2) as per Scenario-1 includes 
> ### 1 input layer with 74 neurons
> ### 4 hidden layers each with 74, 70, 66, 60 neurons respectively and each with "relu" activation function
> ### 1 output layer with a single neuron with "sigmoid" activation function for binary classification output of "credit_default"

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.models import load_model

# Loading the Pre-Trained Target Model 2 (TM2) for Classification Evaluation of "credit_default" as per Scenario-1

tm2_model_path = ""

target_model_2_pre_trained = load_model(tm2_model_path)

print("Target Model 2 Loaded Successfully")

In [ ]:
# Verifying the Summary of the Model

target_model_2_pre_trained.summary()

## Target Model 2 (TM2) Scenario-1 - Validation Evaluation - Classification - "credit_default"

In [ ]:
# Evaluating the Target "credit_default" on the Validation Data as per Scenario-1

tm2_y_pred = target_model_2_pre_trained.predict(tm2_validation_X, batch_size=1)

print("Execution Completed")

In [ ]:
# Verifying the Count of Evaluation Outcomes on the Validation Data as per Scenario-1

print("Total Output Actuals on the Source Model Validation Data: ", tm2_validation_y.shape[0])
print("Total Output Predictions on the Source Model Validation Data: ", len(tm2_y_pred))

In [ ]:
# Comparing the Actual and Prediction Results for the first 10 Validation Data Instances

print("Target Model 2 Validation Actuals")
print(tm2_validation_y[:10])

print("Target Model 2 Validation Predictions")
print(tm2_y_pred[:10])

## Target Model 2 (TM2) Scenario-1 - Actuals versus Predictions Comparison

### Converting the Probability Predictions of the "credit_default" into a Binary Value Representation of 0 and 1

In [ ]:
# Converting probability predictions numpy array into a dataframe

tm2_y_pred_df = pd.DataFrame(tm2_y_pred, columns=['Credit_Default_Probability_Prediction'])
sm_y_pred_df.head()

In [ ]:
tm2_y_pred_df['Credit_Default_Class_Prediction'] = np.where( tm2_y_pred_df['Credit_Default_Probability_Prediction'] >= 0.5, 1, 0)

print("Missing Values in the New Column 'Credit_Default_Class_Prediction':", tm2_y_pred_df['Credit_Default_Class_Prediction'].isna().sum())

print("\n")

# Displaying a sample of 10 random actuals and its respective predictions
tm2_y_pred_df.sample(10)

In [ ]:
# Verifying the Size and the Missing Values (if any) Count of the Score Status Actual (Ground-Truth) Dataframe and the Predictions Dataframe

print(tm2_validation_y.shape)
print(tm2_y_pred_df.shape)

print("\n")

print(tm2_validation_y.isna().sum())
print(tm2_y_pred_df.isna().sum())

In [ ]:
# Concatenating the Credit Default Actual (Ground-Truth) Dataframe and the Predictions Dataframe

frames = [tm2_validation_y, tm2_y_pred_df]

tm2_results = pd.concat(frames, axis=1)

# Renaming the "credit_default" Column Name
tm2_results.rename(columns = {'credit_default':'Credit_Default_Class_Actual'}, inplace = True)

# Displaying a sample of 10 random results
tm2_results.sample(10)

## Target Model 2 (TM2) Scenario-1 - Exporting a Copy of the "credit_default" Output Predictions

In [ ]:
# Exporting a copy of Credit Default Actuals and Predictions DataFrame as a csv file

tm2_results.to_csv("/Users/vidhyalakshmiparthasarathy/.CMVolumes/Google-Drive-pbvidhya/QMUL_MSc_Project/credit_risk_scoring_project/output/tm2_validation_results/tm2_validation_results_epochs_10.csv")

print("Data Export Completed")

## Target Model 2 (TM2) Scenario-1 - Metrics Report

In [ ]:
# Target Model 2 (TM2) Scenario-1 - Classificatio Report 

from sklearn.metrics import confusion_matrix, classification_report

tm2_classification_report = classification_report(tm2_results['Credit_Default_Class_Actual'], tm2_results['Credit_Default_Class_Prediction'])

print(sm_classification_report)

In [ ]:
# Target Model 2 (TM2) Scenario-1 - Confusion Matrix

import tensorflow as tf
import seaborn as sn

tm2_cm = tf.math.confusion_matrix(labels=tm2_results['Credit_Default_Class_Actual'], predictions=tm2_results['Credit_Default_Class_Prediction'])

plt.figure(figsize = (8, 6))
sn.heatmap(tm2_cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

In [ ]:
# Target Model 2 (TM2) Scenario-1 - ROC, AUC

from sklearn.metrics import roc_auc_score

tm2_auc = roc_auc_score(tm2_results['Credit_Default_Class_Actual'], tm2_results['Credit_Default_Class_Prediction'])

print("Source Model ROC AUC: ", sm_auc)